### ISSUE TITLE
insert_df has undocumented side effects

### ISSUE THREAD

**Issue by georgipeev** [ClickHouse/clickhouse-connect#112]
The `insert_df` method can modify its `df` parameter, for example replacing `pandas.NaT` values with `None`. This is not documented and unexpected behavior. Please either fix or document properly.

Python version: 3.9
clickhouse_connect version: 0.5.5

**Comment by genzgd** [comment]
Do you have any other examples (I can see where it's happening for NaT).  Would you be willing to add the appropriate tests?

**Comment by genzgd** [comment]
@georgipeev I couldn't find any other potential mutations and added some basic "the df didn't change" assertions in tests, but please let me know if you find any other similar behavior before I merge the [PR](https://github.com/ClickHouse/clickhouse-connect/pull/113)

**Comment by georgipeev** [comment]
Great, thanks works. Thanks! I haven't seen any other mutations.

**Comment by georgipeev** [comment]
Actually, I found two more related problems whereby the `insert_df` method is mutating its `df` parameter: 
- if `df` has a `numpy.dtype('float64')` column, it's converted to `object`
- if `df` has a `pandas.DatetimeTZDtype(tz='<some timezone>')` column, it's converted to `object`
