### ISSUE TITLE
clickhouse-connect 0.5.2  is not considering proxy variables

### ISSUE THREAD

**Issue by Jishnu-Prakash-K** [ClickHouse/clickhouse-connect#114]
clickhouse-connect 0.5.2  is not considering proxy variables. Added http_proxy, https_proxy. When I try with 0.1.5 version its able to connect. Could someone help with this?

Thanks in advance.

**Comment by genzgd** [comment]
I'm not sure what you mean by "added http_proxy, https_proxy" -- where did you add that?  Also there is not a 0.1.5 release that I know of (and it would have been very old).  Do you mean a different version?  A different project?

In any case the current version doesn't support proxies without using a custom `pool_mgr` argument to the main `get_client` method.  I will look at adding that support.

**Comment by genzgd** [comment]
Are you talking about the environment variables HTTP_PROXY and HTTPS_PROXY?

**Comment by Jishnu-Prakash-K** [comment]
Yeah, its an old version. I'm deploying it in kubernetes, added these variables in deployment file is what I meant.

Anyways version 0.2.7 also works with these variables.

**Comment by genzgd** [comment]
Thanks for the details.  I'm working on a new release that should restore that functionality.  It came "for free" with the requests library but that was removed and I didn't realize it was automatically handling those environment variables.

**Comment by Jishnu-Prakash-K** [comment]
Thanks 👍🏼

**Comment by genzgd** [comment]
This should work with v0.5.7.  Please re-open this issue if you have any problems.  I've tested with a local http and https proxy but that doesn't guarantee it will work in all situations.
