### ISSUE TITLE
insert_df has more undocumented side effects

### ISSUE THREAD

**Issue by georgipeev** [ClickHouse/clickhouse-connect#116]
I found two more problems related to #112 whereby the `insert_df` method is mutating its `df` parameter:
- if `df` has a `numpy.dtype('float64')` column, it's converted to `object`
- if `df` has a `pandas.DatetimeTZDtype(tz='<some timezone>')` column, it's converted to `object`

**Comment by genzgd** [comment]
Could you post the code for a small reproducible example, including the destination column type?

I can't reproduce for float64, for example:

```python
def test_pandas_64bit_types(test_client: Client, table_context: Callable):
    np_floats = np.array([3288.23478284738437, 27482.732781763, 328783824.6828], dtype=np.float64)
    df = pd.DataFrame({'float64': np_floats})
    source_df = df.copy()
    with table_context('test_pandas_64_types', columns=['float64 Float64']):
        test_client.insert_df('test_pandas_64_types', df)
        assert source_df.equals(df)
```

That passed, the df and source_df look identical, and the dtype remains float64.

Thanks!

**Comment by georgipeev** [comment]
Sorry, I should have been a bit more precise. The problem only happens if the corresponding columns in the Clickhouse table are `Nullable`, i.e., the `float64` is a `Nullable(Float64)`, and the `pandas.DatetimeTZDtype(tz=...)` is a `Nullable(DateTime(...))`.
Also, using Python=3.9 and clickhouse-connect=0.5.5.

**Comment by genzgd** [comment]
Okay, I can reproduce on 0.5.5, but I cannot reproduce on 0.5.6 or 0.5.7 (at least for float64).  Can you please test with one of those versions that has the fix for https://github.com/ClickHouse/clickhouse-connect/issues/112?

Thanks!

**Comment by georgipeev** [comment]
I just tested 0.5.7, the two problems above no longer exist there. Thanks!
