### ISSUE TITLE
NULL value in Nullable(String) column returned as empty string

### ISSUE THREAD

**Issue by georgipeev** [ClickHouse/clickhouse-connect#117]
The `clickhouse_connect.driver.httpclient.HttpClient.query_df` method seems to return empty strings instead of `None` where the corresponding value in the Clickhouse table's `Nullable(String)` column is `NULL`.

Python version: 3.9
clickhouse-connect version: 0.5.7

**Comment by genzgd** [comment]
Try setting the `use_none=True` keyword parameter in `query_df`.  By default numpy and pandas queries will return a default value instead of None because using None generally forces an object array which is less efficient, but you can override that behavior with the use_none keyword argument.

**Comment by georgipeev** [comment]
That worked, thanks.
What's sort of weird is that this was not a problem until I updated to version 0.5.7 of clickhouse-connect, and then I couldn't reproduce the old behavior even when I backed the version to 0.5.5.

**Comment by genzgd** [comment]
Updated the docs to note that the default for `use_none` is `False` for numpy and pandas query
