### ISSUE TITLE
When no rows are selected, query_df returns empty list, not empty DataFrame

### ISSUE THREAD

**Issue by georgipeev** [ClickHouse/clickhouse-connect#118]
The docstring of the method promises "Pandas dataframe representing the result set," yet an empty list is returned if the select statement yields no rows. Perhaps an empty dataframe would be a better return value, even better if it could have appropriate columns.

clickhouse-connect version: 0.5.7

**Comment by genzgd** [comment]
Agreed, that's a copy paste error.

**Comment by genzgd** [comment]
Adding columns is not practical however since names and types are not returned by ClickHouse for empty result sets using the Native protocol.

**Comment by georgipeev** [comment]
That sounds reasonable, thanks.
