### ISSUE TITLE
Querying DateTime64(1) columns results in exception

### ISSUE THREAD

**Issue by georgipeev** [ClickHouse/clickhouse-connect#126]
It seems that querying a `DateTime64(1)` column using the `http_client.query_df` (and probably any other query method) results in an exception as shown below. This does not happen with `DateTime64(3)` or `DateTime64(6)` columns. I verified that no exception is thrown if I remove the `DateTime64(1)` column from the select statement.
```
WARNING:clickhouse_connect.driver.httputil:Closed HTTP response due to unexpected exception
Traceback (most recent call last):
  File "/home/gpeev/.tox/default/lib/python3.9/site-packages/clickhouse_connect/driver/transform.py", line 42, in get_block
    column = col_type.read_column(source, num_rows, context)
  File "/home/gpeev/.tox/default/lib/python3.9/site-packages/clickhouse_connect/datatypes/base.py", line 128, in read_column
    column = self.read_column_data(source, num_rows, ctx)
  File "/home/gpeev/.tox/default/lib/python3.9/site-packages/clickhouse_connect/datatypes/base.py", line 143, in read_column_data
    return self._read_column_binary(source, num_rows, ctx)
  File "/home/gpeev/.tox/default/lib/python3.9/site-packages/clickhouse_connect/datatypes/temporal.py", line 151, in _read_binary_naive
    return numpy_conv.read_numpy_array(source, self.np_type, num_rows)
  File "clickhouse_connect/driverc/npconv.pyx", line 13, in clickhouse_connect.driverc.npconv.read_numpy_array
ValueError: cannot create an OBJECT array from memory buffer
```

Python version: 3.9
clickhouse-connect version: 0.5.7

**Comment by genzgd** [comment]
As far as I can tell, there's no real numpy datatype for a time in 10ths of seconds (which is why this fails).  What is the use case for a DateTime64(1) column?

**Comment by georgipeev** [comment]
DateTime64(1) is supported by Clickhouse and, apparently, used in my organization.

**Comment by genzgd** [comment]
Maybe you can cast it to a valid numpy type in your query?  

```sql
-- Show that now64 is stored as a DateTime64(3) -- milliseconds
SELECT toTypeName(now64())

┌─toTypeName(now64())─┐
│ DateTime64(3)       │
└─────────────────────┘

-- cast now() to a DateTime(64, 1)

SELECT toTypeName(CAST(now64(), 'DateTime64(1)'))

Query id: cfc140f8-246a-453c-bbcc-a68822f93050

┌─toTypeName(CAST(now64(), 'DateTime64(1)'))─┐
│ DateTime64(1)                              │
└────────────────────────────────────────────┘

-- Cast a DateTime64(1) to microseconds

SELECT CAST(toDateTime(now64(), 1), 'DateTime64(6)')

┌─CAST(toDateTime(now64(), 1), 'DateTime64(6)')─┐
│                    2023-02-13 16:28:00.500000 │
└───────────────────────────────────────────────┘

```

So in your SELECT query I would suggest casting your DateTime64(1) column to either a DateTime column if seconds are good enough, or a DateTime64(3) column if you want to preserve 10ths of seconds in a numpy `datetime64[ms]` column (which then Pandas can convert to a Pandas Timestamp).

Note that DateTime64(1) actually works okay if you are using Python datatypes:

```python

client.query('SELECT toDateTime64(100000000.2372, 2)').first_row
(datetime.datetime(1973, 3, 3, 9, 46, 40, 230000),)
client.query('SELECT toDateTime64(100000000.2372, 4)').first_row
(datetime.datetime(1973, 3, 3, 9, 46, 40, 237200),)
```

**Comment by georgipeev** [comment]
The workarounds with casting to precision 3 or 6, or querying via `client.query` can certainly be considered, but I don't think it's a great idea to force users to use workarounds to compensate for the lack of support for a particular and perfectly valid Clickhouse type.
If `query_df` will not support `DateTime64(1)` and will raise `ValueError`s, that behavior should be properly documented so the user can at least know that workarounds will be necessary, as opposed to being surprised by an unexpected exception.

**Comment by genzgd** [comment]
Pandas is based on numpy and numpy doesn't support a datatype of "10ths of seconds".  To deal with this edge case in the current optimized code for reading numpy datetime values doesn't make a lot of sense -- I think it would look something like multiplying the incoming ClickHouse value to a "recognized" milli/micro/nanosecond value, which would be much slower than the way it works now. There's also no advantage at to using a a DateTime64(1) over a DateTime(3) -- they use the same storage.

I can document it, but that would include a recommendation to use numpy recognized datatypes if you want to work in dataframes.

**Comment by georgipeev** [comment]
I don't think this is ideal, as it effectively means `query_df` won't support a perfectly valid Clickhouse type because, what ultimately amounts to, "handling the type is too much hassle" and "Clickhouse users should not use that type".

**Comment by genzgd** [comment]
It's not a question of hassle, it's a question of tradeoffs.  I don't want to sacrifice performance for 99% of users who don't use a datatype that makes no sense, and that has an easy workaround.
