### ISSUE TITLE
Timezone-aware DateTime64 columns now returned missing the timezone info

### ISSUE THREAD

**Issue by georgipeev** [ClickHouse/clickhouse-connect#136]
### Describe the bug
Timezone-aware columns in Clickhouse like `(DateTime64(6, 'America/Chicago'))` used to be returned by `query_df` in correspondingly timezone-aware DataFrame columns of type `pandas.DatetimeTZDtype(unit='ns', tz='America/Chicago')` until (at least) version 0.5.7 of clickhouse-connect. In the latest version 0.5.12 such columns are returned as timezone-unaware `numpy.datetime64` columns.

### Steps to reproduce
1. Create a table with a `(DateTime64(6, 'America/Chicago'))` column; insert some data
2. Query the table using `query_df`
3. The dtype of the column in the returned DataFrame will be `pandas.DatetimeTZDtype(unit='ns', tz='America/Chicago')` if using clickhouse-connect version 0.5.7 (i.e., timezone-aware), but `numpy.datetime64` if using clickhouse-connect version 0.5.12 (i.e., timezone-unaware).

### Expected behaviour
Returned colunm dtype is `pandas.DatetimeTZDtype(unit='ns', tz='America/Chicago')`

**Comment by genzgd** [comment]
That is related to https://github.com/ClickHouse/clickhouse-connect/issues/120.

For various obscure historical reasons ClickHouse *does* return the timezone information for a DateTime64 column, but *doesn't* return that information for a DateTime column (in the particular case of HTTP using Native format) so `clickhouse-connect` was not setting timezone for any DateTime column (after the internal switch from RowBinary to Native format).  There's a workaround where the client can specific the timezone as a keyword argument (`query_tz`/`column_tzs`), but even that doesn't work for pandas currently.

I have a fix for the DateTime64 issue, which will also enable the `query_tz`/`column_tzs` workaround.  That fix will probably be released early next week.  Also, in today's release of ClickHouse, there's also a fix for the problem of not returning timezone information for DateTime columns.  However, that will only work with the most recent ClickHouse version 23.2.x and also requires the next `clickhouse-connect` release to handle the low level change.  So eventually, with the latest ClickHouse server and clickhouse-connect version, the workaround won't be necessary.

(Of course, my long standing  -- about 20 years now -- recommendation is **never** store anything related to timezones in your database, just store absolute UTC times, and wait until the final user UI to actually display the adjusted time.  Oh well.)

**Comment by georgipeev** [comment]
In my experience, all timestamps are a pain to work with, but timezone-unaware `DateTime`s in Clickhouse are even harder to deal with than timezone-aware ones, because, empirically, they are assumed to be in the system timezone and then converted to UTC before being inserted in Clickhouse, which is extremely confusing. Writing a `2023/02/23 22:30` timezone-unaware timestamp to a `DateTime` column via either a direct call to `clickhouse-connect`'s `insert_df` or `clickhouse-client` through a flat file ends up writing a timezone-unaware `2023/02/23 16:30` timestamp to the Clickhouse table (probably via the same code path, maybe on the server side) because my system timezone is set to America/Chicago, which is UTC+6. When such timestamps are read back, they need to be localized to UTC, converted to the system default timezone, and then localized to `None` (erasing the timezone info). That's a hassle.

The way `DateTime64(timezone)` was handled by `clickhouse-connect` version 0.5.7 was the most user-friendly, because it needed absolutely no adjustments on either writing or reading. Ideally, `DateTime(timezone)` would work the same, and maybe even timezone-unaware `DateTime` and `DateTime64` would not need any extra conversion work. At the very least, behavior should be deterministic so users can at least code up the right type of timestamp massaging.

As always, your effort for dealing with these issues is much appreciated.

**Comment by genzgd** [comment]
Interesting, I suspect the string conversions to a pandas Timestamp/clickhouse-client flat-file to DateTime which assume the system timezone is probably the culprit in both cases.  I don't know enough about such conversions to know if there is a way to configure them to assume a UTC timestamp from the bare string, but the whole situation is definitely fragile.

In any case the 0.5.7 behavior should work again in the next release -- presumably 0.5.13 -- for DateTime64.  The regression was a side effect of using numpy arrays as the basis for all pandas series (instead of -- in the case of DateTime64 -- a list of Python datetime.datetime objects which were timezone aware).   Unfortunately Python timezone handling is very inefficient, so the fix will come at a performance cost for timezone aware columns, but it should work as expected.
