### ISSUE TITLE
use X-ClickHouse-Timezone http header instead of timezone()

### ISSUE THREAD

**Issue by den-crane** [ClickHouse/clickhouse-connect#138]
https://github.com/ClickHouse/ClickHouse/pull/9493

in the future timezone will be changeable in a session or in a query.

```
select now() settings timezone='Europe/Berlin'
```

**Comment by zvonand** [comment]
it will be changeable as soon as https://github.com/ClickHouse/ClickHouse/pull/44149 is done.

**Comment by genzgd** [comment]
Code to detect a timezone change added in 0.5.17, but not tested where the header result differs from the server timezone, since that code isn't active yet.
