### ISSUE TITLE
Is there a way to use this library or any other in Python to issue queries to clickhouse-local

### ISSUE THREAD

**Issue by sujeetpillai** [ClickHouse/clickhouse-connect#143]
Was unable to find anything in the docs for the same. Clickhouse-local is a cli tool. Is there any way other than to use subprocess and such to run clickhouse-local through python?

**Comment by genzgd** [comment]
Not currently, since clickhouse-connect operates over the http protocol and clickhouse-local does not create an http server.  We've begun exploring a tighter connection, but it will take a fair amount of work.

**Comment by sujeetpillai** [comment]
Thanks for the info. Appreciate the promptness.

**Comment by genzgd** [comment]
@sujeetpillai  a look at https://github.com/auxten/chdb.  If that works for you please let us know!

**Comment by sujeetpillai** [comment]
Thanks. This seems interesting.

**Comment by genzgd** [comment]
We currently recommend using chdb as the way to run an interactive Python session with ClickHouse, especially now that the main developer Auxten Wang has joined ClickHouse Inc. officially and will be providing continuing active support.
