### ISSUE TITLE
Conda packaging

### ISSUE THREAD

**Issue by chairmank** [ClickHouse/clickhouse-connect#150]
[Conda](https://docs.conda.io/en/latest/) is a package manager that is widely used in the Python community. I believe that a significant fraction of Python users would like to be able to install a `clickhouse-connect` Conda package.

If the ClickHouse community is interested in maintaining such a Conda package, I recommend using the organization and infrastructure of [conda-forge](https://conda-forge.org/) to do so. [`clickhouse-driver`](https://github.com/conda-forge/clickhouse-driver-feedstock) is already built and distributed this way.

**Comment by genzgd** [comment]
This seems to be working [now](https://github.com/conda-forge/clickhouse-connect-feedstock), although given the complexities involved it would not surprise me if this breaks going forward.
