### ISSUE TITLE
Unrecognized ClickHouse type base: Point name: Point

### ISSUE THREAD

**Issue by aimfeld** [ClickHouse/clickhouse-connect#151]
**Is your feature request related to a problem? Please describe.**

I currently get the following error when calling `create_insert_context()` with a `Point` column in `column_type_names`:

`Unrecognized ClickHouse type base: Point name: Point`

When looking at the abstract class `ClickHouseType`, I found no extending Point class, so I assume this has not been implemented yet. 

**Describe the solution you'd like**

Support for the `Point` datatype.

**Comment by genzgd** [comment]
Unfortunately that is correct, there is no support for the Geo types yet.
