### ISSUE TITLE
INSERT INTO OR IGNORE

### ISSUE THREAD

**Issue by pvl-k** [ClickHouse/clickhouse-connect#162]
Hello.
I use insert_df Method for load pandas' dataframe to clickhouse.
This way uses "append" method and my data is duplicate more times.
Can you add "if_exists" parameter, like in SQLAlchemy, with different results (ignore, replace, append)?
Thanks a lot.

**Comment by genzgd** [comment]
Unlike a standard relational or document database, ClickHouse is an OLAP data store that normally allows duplicate data (there is an exception for "blocks" that are exactly the same, but I don't think that will fix your issue).  ClickHouse is really designed for fast processing of append only, immutable data, and as part of that high performance design, it has no "unique key" constraints and no simple way to update rows.

Accordingly the best approach is generally to eliminate duplicates before any insert into ClickHouse.  An alternative approach is to remove duplicates "after the fact", using some of the strategies mentioned here:  https://clickhouse.com/docs/en/guides/developer/deduplication.

If you really need update data (or ignore inserted duplicates), ClickHouse might not be the best option.  In any case, adding this kind of functionality into a client like clickhouse-connect is really not feasible.
