### ISSUE TITLE
Clickhouse client init tries to connect to database right away.

### ISSUE THREAD

**Issue by pkit** [ClickHouse/clickhouse-connect#170]
### Describe the bug

When people call `create_client()` they don't usually expect an immediate `SELECT version(), timezone(), currentDatabase()` to be sent.

Why?
Because server may not be up yet? And people want to check that the server is up.
If you create a client it's a bad practice to call stuff in `__init__()`
Cause if something goes wrong in `__init__` your client becomes totally unusable.

### Steps to reproduce
1. `client = create_client(host="localhost")`

### Expected behaviour

Success

Right now to check if server is up you will need to directly call HTTP interface instead of using this client...

**Comment by genzgd** [comment]
Call create_client with a try catch?  There's no point in creating a client without all the information needed from the server, including settings.
