### ISSUE TITLE
Can't filter on DateTime column in Apache superset

### ISSUE THREAD

**Issue by maratbakiev2** [ClickHouse/clickhouse-connect#177]
### Describe the bug
When building dashboards in superset there is a need to have a filter by time range. Setting it for datasource in Clickhouse that is read by clickhouse-connect driver leads to an error.

There was a discussion in superset group #https://github.com/apache/superset/issues/22390
But their view is that it should be fixed on the clickhouse-connect driver side.

This is the error (larger log is below)
`
Error: :HTTPDriver for http://10.100.2.72:8123 returned response code 400)
 Code: 53. DB::Exception: Cannot convert string 2023-04-20 00:00:00.000000 to type DateTime('UTC'): while executing 'FUNCTION greaterOrEquals(fact_new_at : 0, '2023-04-20 00:00:00.000000' : 1) -> greaterOrEquals(fact_new_at, '2023-04-20 00:0
`

### Steps to reproduce
1. create any table in clickhouse with 2 columns - 1 DateTime, another - numeric (could be other types but this is easiest one)
2. connect this table as a dataset in superset. To do that, first create a connection from superset to clickhouse, then press "create dataset" and find the table created on the previous step
3. build any kind of time dependent chart. For example, create time series chart with time values on x axis and sums on y axis.
4. add chart to dashboard. Go to dashboard and press "add filter". Pick time range filter. Try to set last week as default value. Save. And you get an error when superset tries to filter out data only by last week

### Expected behaviour
After applying time range filter dashboard in superset doesn't crash and just filters appropriate values.

### logs taken from superset webserver pod

2023-04-28 08:57:53,906:ERROR:clickhouse_connect.driver.httpclient:Code: 53. DB::Exception: Cannot convert string 2023-04-21 00:00:00.000000 to type DateTime('UTC'): while executing 'FUNCTION greaterOrEquals(fact_new_at : 1, '2023-04-21 00:00:00.000000' : 2) -> greaterOrEquals(fact_new_at, '2023-04-21 00:00:00.000000') UInt8 : 4'. (TYPE_MISMATCH) (version 22.3.19.6 (official build))

Query SELECT toStartOfDay(toDateTime(`fact_new_at`)) AS `__timestamp`,
       count(`order_id`) AS `COUNT(order_id)`
FROM `marts`.`fact_orders`
WHERE `fact_new_at` >= '2023-04-21 00:00:00.000000'
  AND `fact_new_at` < '2023-04-28 00:00:00.000000'
GROUP BY toStartOfDay(toDateTime(`fact_new_at`))
ORDER BY `COUNT(order_id)` DESC
LIMIT 10000 on schema marts failed
Traceback (most recent call last):
  File "/app/superset/connectors/sqla/models.py", line 1920, in query
    df = self.database.get_df(sql, self.schema, mutator=assign_column_label)
  File "/app/superset/models/core.py", line 458, in get_df
    self.db_engine_spec.execute(cursor, sqls[-1])
  File "/app/superset/db_engine_specs/base.py", line 1261, in execute
    raise cls.get_dbapi_mapped_exception(ex)
  File "/app/superset/db_engine_specs/base.py", line 1259, in execute
    cursor.execute(query)
  File "/usr/local/lib/python3.8/site-packages/clickhouse_connect/dbapi/cursor.py", line 50, in execute
    query_result = self.client.query(operation, parameters)
  File "/usr/local/lib/python3.8/site-packages/clickhouse_connect/driver/client.py", line 178, in query
    return self._query_with_context(query_context)
  File "/usr/local/lib/python3.8/site-packages/clickhouse_connect/driver/httpclient.py", line 207, in _query_with_context
    response = self._raw_request(body,
  File "/usr/local/lib/python3.8/site-packages/clickhouse_connect/driver/httpclient.py", line 387, in _raw_request
    self._error_handler(response)
  File "/usr/local/lib/python3.8/site-packages/clickhouse_connect/driver/httpclient.py", line 323, in _error_handler
    raise OperationalError(err_str) if retried else DatabaseError(err_str) from None
clickhouse_connect.driver.exceptions.DatabaseError: :HTTPDriver for http://chi-simple-nonreplicated-0-0.stable.svc.cluster.local:8123 returned response code 400)
 Code: 53. DB::Exception: Cannot convert string 2023-04-21 00:00:00.000000 to type DateTime('UTC'): while executing 'FUNCTION greaterOrEquals(fact_new_at : 1, '2023-04-21 00:00:00.000000' : 2) -> greaterOrEquals(fact_new_at, '2023-04-21 00:0
2023-04-28 08:57:53,907:WARNING:superset.connectors.sqla.models:Query SELECT toStartOfDay(toDateTime(`fact_new_at`)) AS `__timestamp`,
       count(`order_id`) AS `COUNT(order_id)`
FROM `marts`.`fact_orders`
WHERE `fact_new_at` >= '2023-04-21 00:00:00.000000'
  AND `fact_new_at` < '2023-04-28 00:00:00.000000'
GROUP BY toStartOfDay(toDateTime(`fact_new_at`))
ORDER BY `COUNT(order_id)` DESC
LIMIT 10000 on schema marts failed
Traceback (most recent call last):
  File "/app/superset/connectors/sqla/models.py", line 1920, in query
    df = self.database.get_df(sql, self.schema, mutator=assign_column_label)
  File "/app/superset/models/core.py", line 458, in get_df
    self.db_engine_spec.execute(cursor, sqls[-1])
  File "/app/superset/db_engine_specs/base.py", line 1261, in execute
    raise cls.get_dbapi_mapped_exception(ex)
  File "/app/superset/db_engine_specs/base.py", line 1259, in execute
    cursor.execute(query)
  File "/usr/local/lib/python3.8/site-packages/clickhouse_connect/dbapi/cursor.py", line 50, in execute
    query_result = self.client.query(operation, parameters)
  File "/usr/local/lib/python3.8/site-packages/clickhouse_connect/driver/client.py", line 178, in query
    return self._query_with_context(query_context)
  File "/usr/local/lib/python3.8/site-packages/clickhouse_connect/driver/httpclient.py", line 207, in _query_with_context
    response = self._raw_request(body,
  File "/usr/local/lib/python3.8/site-packages/clickhouse_connect/driver/httpclient.py", line 387, in _raw_request
    self._error_handler(response)
  File "/usr/local/lib/python3.8/site-packages/clickhouse_connect/driver/httpclient.py", line 323, in _error_handler
    raise OperationalError(err_str) if retried else DatabaseError(err_str) from None
clickhouse_connect.driver.exceptions.DatabaseError: :HTTPDriver for http://chi-simple-nonreplicated-0-0.stable.svc.cluster.local:8123 returned response code 400)
 Code: 53. DB::Exception: Cannot convert string 2023-04-21 00:00:00.000000 to type DateTime('UTC'): while executing 'FUNCTION greaterOrEquals(fact_new_at : 1, '2023-04-21 00:00:00.000000' : 2) -> greaterOrEquals(fact_new_at, '2023-04-21 00:0

#### Environment
* clickhouse-connect version: 0.5.21
* Python version: 3.8.12

#### ClickHouse server
* ClickHouse Server version: 22.3.19.6
* ClickHouse Server non-default settings, if any: no
* `CREATE TABLE` statements for tables involved: 
` create table marts.fact_orders (fact_new_at DateTime('UTC'), num_orders UInt16)`

Would love this problem to be fixed. I can assist in reproducing the bug on the call and testing the fix

**Comment by genzgd** [comment]
It looks like the underlying problem in  https://github.com/apache/superset/issues/22390 was that the target ClickHouse column was a `Date` column, not a DateTime.  In general DateTime filters have worked in the past, so I'm wondering if there is something new in this area in Superset.  What version of Superset are you using so we can try to reproduce?

**Comment by genzgd** [comment]
The problem looks like it's related to the fact that Superset is sending a string with fractional seconds in the filter, which perhaps it didn't do before.

**Comment by maratbakiev2** [comment]
@genzgd I'm using superset 2.0.1
Can't comment on whether they done it before or not, because I haven't used earlier version. If it's important I can roll back superset and test this case on previous version

**Comment by genzgd** [comment]
Thanks, we'll take a look.  One more question -- does it work correctly for DateTime columns without a timezone?

**Comment by maratbakiev2** [comment]
Oh, it does!

Steps I've taken:
1.  `alter table marts.fact_orders modify column fact_new_at DateTime();`
2. Go to Datasets in Superset and re-sync metadata with table in CH
3. Go to dashboards and apply filter. It worked

Then I've switched back
1. `alter table marts.fact_orders modify column fact_new_at DateTime('UTC');`
2. Go to Datasets in Superset and re-sync metadata with table in CH
3. Go to dashboards and apply filter. It crashed with the error I sent above

 @genzgd is it something that could be fixed within couple of weeks or it will take longer? I'm asking because based on the answer I will take different paths on my side.

**Comment by genzgd** [comment]
That sounds like it should be a fairly easy fix, but it's likely to be in the Superset project not `clickhouse-connect`, since it involves building the filter query.  So it would presumably not be available until another Superset release unless you run Superset directly from source/Github.

If you can get away without using a DateTime with a timezone (the value is stored in ClickHouse as a Unix Epoch timestamp regardless) I would recommend that as a general practice anyway.  It's normally more efficient for ClickHouse to deal with that.

**Comment by maratbakiev2** [comment]
So, to recap:
1. issue is not about any DateTime column, only the DateTime(timezone) column
2. should be fixed on superset side
