### ISSUE TITLE
Accept `external_data` in the `query_arrow` method

### ISSUE THREAD

**Issue by cpcloud** [ClickHouse/clickhouse-connect#183]
**Is your feature request related to a problem? Please describe.**

Not related to a problem.

**Describe the solution you'd like**

I'd like to be able to pass external data to the `query_arrow` method.

```python
con.query_arrow(..., external_data=external_data)
```

**Describe alternatives you've considered**

I have to use `query_df` to do this, or one of the other `query_*` methods that accepts `external_data`.

**Additional context**

N/A

**Comment by genzgd** [comment]
Thanks for the report!  This was an oversight that should be fixed in the next release.
