### ISSUE TITLE
`query_arrow` is unusable if results contain strings and server cannot be configured by the user

### ISSUE THREAD

**Issue by cpcloud** [ClickHouse/clickhouse-connect#184]
### Describe the bug

Whether I can run `query_arrow` at all depends on whether I can configure server side settings. It doesn't seem to matter whether I pass `use_strings=True` or `use_strings=False`

This is a suboptimal user experience. It's not clear why the client must be able to configure the server to request results in a different format.

### Steps to reproduce
1. Run `query_arrow(...)` against the clickhouse playground.

### Expected behaviour

A successfully executed query

### Code example
```
In [15]: import clickhouse_connect as cc

In [16]: con = cc.create_client(
    ...:     host="play.clickhouse.com",
    ...:     port=443,
    ...:     user="play",
    ...:     secure=True,
    ...:     password="clickhouse",
    ...: )

In [17]: con.query_arrow("show tables")
...
ProgrammingError: Setting output_format_arrow_string_as_string is unknown or readonly
```

### clickhouse-connect and/or ClickHouse server logs

I'm not sure how to access either of those logs.

#### Environment
* clickhouse-connect version: 0.5.22
* Python version: 3.10.11
* Operating system: Linux

#### ClickHouse server
* ClickHouse Server version: 23.5.1.291
* ClickHouse Server non-default settings, if any: No idea, I don't manage the server.
* `CREATE TABLE` statements for tables involved: None

**Comment by genzgd** [comment]
Thanks for the detailed report!  This should be fixed in the 0.5.23 version which will be released shortly.
