### ISSUE TITLE
Cannot use `external_data` in CTAS query

### ISSUE THREAD

**Issue by cpcloud** [ClickHouse/clickhouse-connect#186]
### Describe the bug

Using an external table in a CTAS (create table as select) query fails saying the external table doesn't exist

### Steps to reproduce

See the code below

### Expected behaviour

I expect to be able to use external data when running a CTAS query.

### Code example
```python
import clickhouse_connect as cc
from clickhouse_connect.driver.client import ExternalData

con = cc.get_client()
query = (
    "CREATE OR REPLACE TABLE t (a Nullable(Int64)) ENGINE = Memory AS SELECT * FROM ext"
)
external_data = ExternalData()
external_data.add_file(
    file_name="ext", data="1\n3", structure=["a Nullable(Int64)"], fmt="CSV"
)
con.query(query, external_data=external_data)
```

### clickhouse-connect and/or ClickHouse server logs

```
clickhouse_connect.driver.exceptions.DatabaseError: :HTTPDriver for http://localhost:8123 returned response code 404)
 Code: 60. DB::Exception: Table default.ext doesn't exist. (UNKNOWN_TABLE) (version 23.4.1.1943 (official build))
```

#### Environment
* clickhouse-connect version: 0.5.23
* Python version: 3.10.11
* Operating system: Linux

#### ClickHouse server
* ClickHouse Server version: 23.4.1.1943
* ClickHouse Server non-default settings, if any: None that I am aware of
* `CREATE TABLE` statements for tables involved: Visible in the code example

**Comment by genzgd** [comment]
This is a side effect of code that tries to avoid streaming results for queries that actually don't return data (diverting them to the `command` function instead.  It's fairly easily fixable but there probably won't be a new release for a week or so.

In the meantime I think you can get around this using the `raw_query` method client method.

**Comment by cpcloud** [comment]
I worked around it in a slightly different way which was to create -> insert -> rename. I'll try `raw_query`.

**Comment by cpcloud** [comment]
`raw_query` works, thanks again!
