### ISSUE TITLE
Getting warnings when installing clickhouse-connect without numpy

### ISSUE THREAD

**Issue by gfleischer-meta** [ClickHouse/clickhouse-connect#195]
when I include clickhouse_connect in my requirements.txt file and receive the following error message: 
clickhouse_connect.driver.ctypes[10]: WARNING Unable to connect ClickHouse Connect C to Numpy API [No module named 'numpy'], falling back to pure Python."

I know installing numpy will solve this issue but I don't want to install numpy and I don't need numpy for my use case( fetch data from clickhosueDB)
One alternative I have considered is specifying an older version of clickhouse_connect that doesn't have numpy as a dependency. However, this may mean missing out on bug fixes and new features introduced in later versions.

I am not using numpy in my project, and I would prefer to avoid unnecessary dependencies to keep my project lightweight.

**Comment by genzgd** [comment]
My apologies for that, it should never have been a warning since numpy is definitely not required if you aren't using it (or pandas).  

The warning can be safely ignored and will be reduced to a debug message in the next release (which I'm hoping will be this week.)
