### ISSUE TITLE
ClickHouse disappear in Superset's new database setup when updates version from 0.5.25 to 0.6.2

### ISSUE THREAD

**Issue by mtieuso** [ClickHouse/clickhouse-connect#205]
### Describe the bug
ClickHouse connector (ver0.6.2) disappear in Superset (ver2.0)
### Steps to reproduce
1. update clickhouse-connect from 0.5.x to 0.6.2
2. clickhouse connector disappear in the list of supported database in Superset (when create new database)
3. all charts, queries related to current clickhouse connection also fail to run

### Expected behaviour
1. clickhouse connector (ver 0.6.x) appear in the list of database in Superset
2. all charts, queries related to clickhouse also success to run

### clickhouse-connect and/or ClickHouse server logs
- logs is not recorded

### temporary solution
- revert lib to 0.5.25, issue is fixed

#### Environment
* clickhouse-connect version: 0.6.2
* Python version: 3.8
* Operating system: Linux

**Comment by genzgd** [comment]
Please see the [READ ME](https://github.com/ClickHouse/clickhouse-connect/blob/main/README.md) or [CHANGELOG](https://github.com/ClickHouse/clickhouse-connect/blob/main/CHANGELOG.md).  If you must use Superset versions prior to 2.1, you have to use the older version of clickhouse-connect.

**Comment by mtieuso** [comment]
thanks, I missed this ChangeLog.
