### ISSUE TITLE
Cannot use SETTINGS statement due to FORMAT Native suffix

### ISSUE THREAD

**Issue by StevenReitsma** [ClickHouse/clickhouse-connect#211]
### Describe the bug
When using dbt to create models, we sometimes need to add a `SETTINGS` statement to a query, for example to specify `schema_inference_hints` for a `DESC` query. For example:

`DESC format(JSONEachRow, '{"id" : 1, "age" : 25, "name" : "Josh", "status" : null, "hobbies" : ["football", "cooking"]}') SETTINGS schema_inference_hints = 'age LowCardinality(UInt8), status Nullable(String)', allow_suspicious_low_cardinality_types=1`

Unfortunately, when using `dbt-clickhouse`, this gives an error, due to the fact that `clickhouse-connect` adds the `FORMAT Native` suffix to every query. Specifically, this is done here: https://github.com/ClickHouse/clickhouse-connect/blob/main/clickhouse_connect/driver/httpclient.py#L169

The resulting query that `clickhouse-connect` sends to ClickHouse looks like this:

`DESC format(JSONEachRow, '{"id" : 1, "age" : 25, "name" : "Josh", "status" : null, "hobbies" : ["football", "cooking"]}') SETTINGS schema_inference_hints = 'age LowCardinality(UInt8), status Nullable(String)', allow_suspicious_low_cardinality_types=1 FORMAT Native`

Which is not a valid query, because the `SETTINGS` clause needs to be last in the statement.
I know it's possible to specify `SETTINGS` in the dbt model parameters itself, but we need to specify this on a per-query basis for our usecase.

I'm not sure if this is actually a problem of `clickhouse-connect` or `dbt-clickhouse`, but it would be great if the function that adds this statement would be smart enough to inject the `FORMAT Native` clause *before* the `SETTINGS` clause, if it detects that the `SETTINGS` clause is present.

### Steps to reproduce
1. In a dbt model, run the `DESC format(JSONEachRow, '{"id" : 1, "age" : 25, "name" : "Josh", "status" : null, "hobbies" : ["football", "cooking"]}') SETTINGS schema_inference_hints = 'age LowCardinality(UInt8), status Nullable(String)', allow_suspicious_low_cardinality_types=1` query
2. Inspect the ClickHouse query log to see that `FORMAT Native` is appended to the query

### Expected behaviour
`FORMAT Native` should be added between the query and the `SETTINGS` clause, instead of just appending it to the query.

#### Environment
* dbt-clickhouse version: 1.4.2
* clickhouse-connect version: 0.5.24
* Python version: 3.10.6
* Operating system: Ubuntu 22.04

#### ClickHouse server
* ClickHouse Server version: 23.3.5.9
* ClickHouse Server non-default settings, if any: nothing relevant, I think
* `CREATE TABLE` statements for tables involved: https://clickhouse.com/docs/en/interfaces/schema-inference
* Sample data for these tables: https://clickhouse.com/docs/en/interfaces/schema-inference

Thanks in advance!

**Comment by genzgd** [comment]
As you probably gathered, FORMAT Native is required in the query to return data that clickhouse-connect can understand.  Attempting to parse the SETTINGS clause is possible and insert the FORMAT in the right place is possible but error prone. In general SQL parsing is a difficult problem usually solved with a sophisticated AST parser, which is not something I want to try to duplicate in Python.

In clickhouse-connect the standard way of sending settings is to use a settings argument with a dictionary, which avoids parsing complexity.  So I'd really consider this a DBT problem, which needs a better way to add ClickHouse settings as part of the configuration.

**Comment by pkit** [comment]
> In general SQL parsing is a difficult problem usually solved with a sophisticated AST parser, which is not something I want to try to duplicate in Python.

https://github.com/tobymao/sqlglot is a python-native no-deps SQL parser.

**Comment by pkit** [comment]
BTW, setting `X-ClickHouse-Format` header in request is handled by CH HTTP server too.

**Comment by genzgd** [comment]
`X-ClickHouse-Format` would be a better option, although using custom headers can cause issues with certain proxy servers.  (Currently the only custom headers that clickhouse-connect sends are those required for mutual TLS authentication with client certificates.)  Maybe I could make using that header (instead of appending Format) a configuration setting that could be controlled in the DBT profile.

**Comment by pkit** [comment]
Yup, appending stuff to SQL query is pretty intrusive.
I hope it doesn't append anything to `command()` :)

**Comment by StevenReitsma** [comment]
Fixed via https://github.com/ClickHouse/ClickHouse/pull/51899. Thanks all!
