### ISSUE TITLE
Wide dataframes cause issues with query string length limits

### ISSUE THREAD

**Issue by aven-mathew** [ClickHouse/clickhouse-connect#213]
### Describe the bug
We have a small number of pivot tables that have large numbers of columns (~900). When attempting to insert this using insert_df we are running into 414 errors over HTTP due to limits set on the AWS ALB we currently have sitting in front of our clickhouse instance. This is due to the [16k limit on the URL](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-limits.html) size that we, unfortunately, cannot adjust. That is definitely larger than the generally accepted limitation of 2048 characters. 

### Steps to reproduce
1. Use wide dataframe.
2. Pass through a load balancer or similar proxy system (nginx) with a limit on the query size.
3. Query returns 414 error.

### Expected behavior

One option would be to allow overriding the column_names to * but in general this limit is definitely reachable with the current query param approach. Ideally restructuring the insert so that the query is part of the body would help this though may have impacts on the performance.

#### Environment
* clickhouse-connect version: 0.6.4
* Python version: 3.8.13

#### ClickHouse server
* ClickHouse Server version: 23.5

**Comment by genzgd** [comment]
This is somewhat tricky in case of the default streaming block inserts, but it looks like it should be doable.  It's hard to imagine that table with 900 columns are good idea though :)

**Comment by pkit** [comment]
Tables with 1000 columns are not rare in AI/ML world, 'cos these are the "features".
