### ISSUE TITLE
Documentation confusion regarding Tuples

### ISSUE THREAD

**Issue by gregersn** [ClickHouse/clickhouse-connect#215]
### Describe the bug

I am trying to insert data into a named Tuple object. 
Under write formats in the documentation here; https://clickhouse.com/docs/en/integrations/python, it mentions that native Python format for a Tuple can be a tuple, or a dict. 
Since I am working with named tuples, I am deducing that I can use a dict as a value to insert data.

### Steps to reproduce
1. Create table with named dict: `CREATE TABLE test_document (t Tuple(s String, i Int32)) engine=Memory`
2. Try insertion of data `client.insert('test_document', [[{'s': 'a', 'i': 5}]])`

### Expected behaviour

Data to be inserted in the table

### clickhouse-connect and/or ClickHouse server logs

Errors out with ` Failed: [undefined]KeyError: 0`
`>   elem_size += e_type.data_size([x[ix] for x in sample])` in `container.py`

From what I can see there is no consideration for `dict` in the code, so I am gathering that the documentation is wrong on this?

**Comment by genzgd** [comment]
Unfortunately you are correct, the documentation is wrong.  There's currently no support for inserting named tuples as Python dictionaries.

The Native format that `clickhouse-connect` uses for inserts has no awareness of named tuples.  For reading data, what it does is read the underlying tuple, then populate a dictionary by matching the declared name in the ClickHouse column type by position.  

We'll have to do something similar for inserts into a Tuple column -- that is, iterate through each dictionary and create a correctly ordered tuple for insert.  You can do this yourself as a workaround but I'll see if I can add the functionality in the next release or two.
