### ISSUE TITLE
❗️❗️❗️ Bug with insert dataframe to field with type Enum8 ❗️❗️❗️

### ISSUE THREAD

**Issue by khmelevskiy** [ClickHouse/clickhouse-connect#219]
### Describe the bug
Bug with insert dataframe into column with type `Enum8`

### Steps to reproduce
1. Create table in clickhouse
``` sql
CREATE TABLE db_test.test
(
    Name String,
    Age  Int32,
    City Enum8('Moscow' = 0, 'Rostov' = 1, 'Kiev' = 2)
) ENGINE = MergeTree()
    ORDER BY Name;
```
2. run code:
``` python 
import clickhouse_connect

clickhouse_connect_client_test = clickhouse_connect.get_client(
        **{
            "username": "",
            "password": "",
            "host": "",
            "port": 443,
            "secure": False,
            "connect_timeout": 30,
            "query_limit": 0,
        },
    )

df_test = pd.DataFrame(
        {
            "Name": ["Alex", "Elena", "Maria"],
            "Age": [25, 30, 35],
            "City": [0, 1, 2],  # "Moscow", "Rostov", "Kiev"
        }
    )

clickhouse_connect_client_test.insert_df(df=df_test, table="db_test.test")
```
3. Result in City column: 
``` sql
SELECT
    *
  FROM
      db_test.test;
```
you see all `Moscow` (=0).

#### Environment
* clickhouse-connect version: 0.6.5
* Python version: 3.9
* Operating system: MacOS 13.4.1
* ClickHouse Server version: 23.5.3.24

**Comment by khmelevskiy** [comment]
the problem is not observed in version 0.5.2

**Comment by khmelevskiy** [comment]
@genzgd hello my friend, sorry for the ping but we are in big trouble with this problem.
Maybe you know where the error is.
We have a lot of incorrect data because of this((

Regards, 
Alexander

**Comment by khmelevskiy** [comment]
I got to [here](https://github.com/ClickHouse/clickhouse-connect/blob/6928aed5845c944007b6bf93e806313a96a93fbc/clickhouse_connect/driver/client.py#L688C11-L688C11) and the data is fine, but incorrect data appears in the clickhouse

**Comment by genzgd** [comment]
My sincere apologies, I have a fix and will release shortly.

The problem is here:

```python
        if first is None or isinstance(first, int):
            if self.nullable:
                column = [0 if not x else x for x in column]
            write_array(self._array_type, column, dest)
```

This is code where the driver decides to write the direct integer into the enum column, or to look up the expected value with a string key.   As updated, the first value is now a numpy int64, not a Python int, so the code tries the lookup.

**Comment by khmelevskiy** [comment]
Could you take me hyperlink where the problem is?

**Comment by genzgd** [comment]
https://github.com/ClickHouse/clickhouse-connect/blob/main/clickhouse_connect/datatypes/numeric.py#L221-L229
