### ISSUE TITLE
Query_arrow gives wrong output with string to date type casting

### ISSUE THREAD

**Issue by rongxin-yu** [ClickHouse/clickhouse-connect#227]
### Describe the bug
Running the same query with query_df and query_arrow returns different result. query_df gives datetime64 as expected, but query_arrow gives uint16
### Steps to reproduce
Follow the code examples below

### Expected behaviour
Both query should return '2023-01-11` with datetime64 type
### Code example
```python
import clickhouse_connect
con = clickhouse_connect.get_client()
con.query_df("select cast('20230111', 'date')")
con.query_arrow("select cast('20230111', 'date')")
```

#### Environment
* clickhouse-connect version: 0.5.25
* Python version: 3.8
* Operating system:

#### ClickHouse server
* ClickHouse Server version:
* ClickHouse Server non-default settings, if any:
* `CREATE TABLE` statements for tables involved:
* Sample data for these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary

**Comment by genzgd** [comment]
Unfortunately this is beyond the control of `clickhouse-connect`.   The ClickHouse server generates the response using the Arrow output format, which is deserialized by the `pyarrow` third party library.  So the problem probably is with the Arrow format in the main ClickHouse server, and I would look for or open an issue in the main ClickHouse repository.

**Comment by rongxin-yu** [comment]
> Unfortunately this is beyond the control of `clickhouse-connect`. The ClickHouse server generates the response using the Arrow output format, which is deserialized by the `pyarrow` third party library. So the problem probably is with the Arrow format in the main ClickHouse server, and I would look for or open an issue in the main ClickHouse repository.

Thank you
