### ISSUE TITLE
Better error messages on inserts (`ProgrammingError` for invalid types)

### ISSUE THREAD

**Issue by carterjfulcher** [ClickHouse/clickhouse-connect#229]
I'm inserting a large data frame, with over a million rows. The following error is raised:

```shell
raise ProgrammingError('Internal serialization error.  This usually indicates invalid data types ' +
clickhouse_connect.driver.exceptions.ProgrammingError: Internal serialization error.  This usually indicates invalid data types in an inserted row or column
```

This error is not falsely triggered, it just doesn't provide any useful information towards debugging the error. I don't know which column has this type error, much less which row. 

Edit: This may not be possible to fix without an upstream Clickhouse API modification. 

From source (`driver/httpclient.py`)
```python3 
    def error_handler(response: HTTPResponse):
            # If we actually had a local exception when building the insert, throw that instead
            if context.insert_exception:
                ex = context.insert_exception
                context.insert_exception = None
                raise ProgrammingError('Internal serialization error.  This usually indicates invalid data types ' +
                                       'in an inserted row or column') from ex  # type: ignore
            self._error_handler(response)
```

**Comment by genzgd** [comment]
You should have the full stack trace in your logs, which can provide a clue?

**Comment by genzgd** [comment]
Column name and full stack trace should be available for these kinds of errors starting with v0.6.9.  Because of the way that columns are generated, it's normally not possible to determine what particular row in the column insert would have caused the exception, so that level of debugging information will not normally be available.
