### ISSUE TITLE
LowCardinality(String) read via query_arrow returned as categoricals with incorrect index type

### ISSUE THREAD

**Issue by georgipeev** [ClickHouse/clickhouse-connect#230]
### Describe the bug
When Clickhouse columns of type `LowCardinality(String)` are queried via `query_df`, they are returned as strings (`pandas` dtype `string[python]`), which may be suboptimal but is not incorrect.

When such columns are queried via `query_arrow`, they are returned as a categorical field in the resulting `pyarrow.Table`, i.e., the column type is `pyarrow.DictionaryType`. Crucially, the `index` type of that `DictionaryType` is set to either `int8` or `int16` (uncertain how that is chosen), which is insufficient when the query produces a large number of unique values. Empirical evidence suggests that, unintuitively, a `DictionaryType` with an `int8` index can hold up to 8193 distinct values, and one with an `int16` index can contain up to 24577 values. As a result, the `pyarrow.Table` returned contains incorrect values for that column, as evidenced by, for example, its `value_counts()`.

Further problems occur if the returned `pyarrow.Table` is, for example, converted into a `polars.DataFrame`, such as the following:
```
  File "/home/gpeev/python3.9/site-packages/pyarrow/compute.py", line 400, in cast
    return call_function("cast", [arr], options, memory_pool)
  File "pyarrow/_compute.pyx", line 572, in pyarrow._compute.call_function
  File "pyarrow/_compute.pyx", line 367, in pyarrow._compute.Function.call
  File "pyarrow/error.pxi", line 144, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 100, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Integer value -128 not in range: 0 to 127
```
Indicating that the index type is inadequate, resulting in an overflow. Attempting to circumvent that by changing the type of all `DictionaryType` columns in the `pyarrow.Table` does not work either, ultimately producing failures such as that:
```
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /home/runner/work/polars/polars/crates/polars-core/src/chunked_array/logical/categorical/builder.rs:112:42
Traceback (most recent call last):
  File "/home/gpeev/pycharm-2021.3.2/plugins/python/helpers/pydev/_pydevd_bundle/pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
  File "/home/gpeev/python3.9/site-packages/polars/series/series.py", line 974, in __getitem__
    return self._s.get_idx(item)
pyo3_runtime.PanicException: called `Option::unwrap()` on a `None` value
```

### Steps to reproduce

1. Create a Clickhouse table with a `LowCardinality(String)` column, say `x`.
2. Insert many unique values, for example 100000, one of each.
3. Query all rows in the table using `query_arrow`.
4. Observe that the `x` column of the `pyarrow.Table` returned by `query_arrow` does not contain 100000 unique values, but far fewer, and that some values are repeated (i.e., the `value_counts()` add up to 100000, but are not all 1s).

### Expected behaviour

The `pyarrow.Table` returned by `query_arrow` should contain the correct values in a column of a type that supports them, that is, either a `string` column (similar to what `query_df` does), or a `DictionaryType` with a sufficiently large index type, such as `int64`.

### Code example
```python
import clickhouse_connect

def test_arrow_categoricals(**params):
        client = clickhouse_connect.get_client(**params)
        client.command("create table test_cat (`i` Int64, `x` LowCardinality(String)) engine=MergeTree order by i")
        n = 100000
        df = pd.DataFrame({"i": range(n), "x": [f"x_{i:05d}" for i in range(n)]})
        client.insert_df(table, df)
        # Pandas works correctly
        res_pd = client.query_df("select * from test_cat")
        print("pandas", len(res_pd["x"].value_counts()))
        # Arrow does not work correctly
        res_ar = client.query_arrow("select * from test_cat")
        print("arrow", len(res_ar["x"].value_counts()))
```
When executed, this prints out:
```
pandas 100000
arrow 24577
```

#### Environment
* clickhouse-connect version: 0.5.20
* Python version: 3.9.17
* Operating system: RHEL 8.6

#### ClickHouse server
* ClickHouse Server version: 22.8.16 revision 54460

**Comment by genzgd** [comment]
Thanks for the report.

Similar to https://github.com/ClickHouse/clickhouse-connect/issues/227, Arrow serialization and deserialization is not really within the scope of the `clickhouse-connect` library.  The arrow format is produce by the ClickHouse server and consumed by the pyarrow library without any intermediate processing.

In this case, it looks like this could be a known issue that may have been fixed here:  https://github.com/ClickHouse/ClickHouse/pull/48361.  Can you test the behavior on a more recent ClickHouse version?

**Comment by georgipeev** [comment]
Thanks for the prompt and useful response!
It seems that this might, indeed, be a server-side issue that was, unfortunately, fixed in a version later than the one I'm using. I will test if the same problem occurs when I query the Clickhouse server via a different route, the command-line `clickhouse-client` tool, which supports Arrow and ArrowStream formats. If the problem persists, that would be a definitive sign the problem is on the server side. If not, we might be able to play with options passed to the `pyarrow.ipc.RecordBatchFileReader` in `clickhouse_connect.driver.query.to_arrow` (line 487), where currently the reader constructed ends up with a schema that has insufficiently large categorical indices.

**Comment by genzgd** [comment]
Just a thought that there may be another server side bug.  My assumption would that if `output_format_arrow_low_cardinality_as_dictionary` is set to `0` (the default), that a LowCardinality(String) column would return Array string values (or binary values, depending on the setting `output_format_arrow_string_as_string`.  Assuming you haven't changed that default, I wonder if the `output_format_arrow_low_cardinality_as_dictionary` is not working as intended.

**Comment by georgipeev** [comment]
I can confirm that this is a server-side issue.
Running the query via the command-line `clickhouse-client` with `--format Arrow` produces the same problem when executed with the `--output_format_arrow_low_cardinality_as_dictionary 1` parameter - `LowCardinality(String)` are read as `pyarrow.DictionaryType` with an insufficiently large `int32` index, so column values are wrong. Omitting that parameter results in a string/binary column type, which is correct.
Is there a way to tell `clickhouse_connect` to not send `output_format_arrow_low_cardinality_as_dictionary` to the server? I don't see where I'm changing that setting in my code, so I would expect it to have the default value you mention, 0. Judging from the result returned by the server, it seems it doesn't.

**Comment by genzgd** [comment]
You can always try to set `{'output_format_arrow_low_cardinality_as_dictionary':0}` specifically as a member of `settings` dictionary in the `query_arrow` method call or the overall `get_client` call and it should be applied by the ClickHouse server.  It does not send that setting otherwise, so I'm still confused as to why it behaves differently in `clickhouse-connect` vs `clickhouse-client`

**Comment by georgipeev** [comment]
I confirm that this `setting` fixes the problem - the LowCardinality strings are then returned as strings. That should suffice until we upgrade the Clickhouse server version.
Thanks for your help!

**Comment by georgipeev** [comment]
The underlying issue is the server-side problem mentioned by @genzgd, https://github.com/ClickHouse/ClickHouse/pull/48361.
