### ISSUE TITLE
can't resolve duplicates problem 

### ISSUE THREAD

**Issue by arthur19q3** [ClickHouse/clickhouse-connect#237]
i am wrting this script to recursively find a few csv files and save them to my database,
even though i am usigng ReplacingMergeTree()
and have set the primamry, when ths script is executed more than once ,  there are duplicates of data ..

```python
from clickhouse_driver import Client
import os
import clickhouse_connect
from clickhouse_connect.driver.tools import insert_file

# Create ClickHouse connection
client = clickhouse_connect.get_client(host='localhost', user='default', password='the17th', database='default')

# client = Client(host='localhost', port=9000, user='default', password='the17th', database='default')
# csv_folder_path = '/home/arthur/Documents/commodities'
csv_folder_path = '/opt/sample/'

# Specify the prefix for the files and the table name
file_prefix = "CU88"
table_name = file_prefix

# Create table SQL command if it doesn't exist
create_table_sql = f"""
CREATE TABLE IF NOT EXISTS {table_name}
(
    `datetime` DateTime64,
    `tradecode` String,
    `openprice` Float32,
    `lastprice` Float32,
    `highprice` Float32,
    `lowprice` Float32,
    `openinterest` Float32,
    `totalturnover` Float32,
    `tradevolume` Float32,
    `sell1price` Float32,
    `sell2price` Float32,
    `sell3price` Float32,
    `sell4price` Float32,
    `sell5price` Float32,
    `sell1volume` Float32,
    `sell2volume` Float32,
    `sell3volume` Float32,
    `sell4volume` Float32,
    `sell5volume` Float32,
    `buy1price` Float32,
    `buy2price` Float32,
    `buy3price` Float32,
    `buy4price` Float32,
    `buy5price` Float32,
    `buy1volume` Float32,
    `buy2volume` Float32,
    `buy3volume` Float32,
    `buy4volume` Float32,
    `buy5volume` Float32,
    `contractmultiplier` Float32,
    `exchange` String
) ENGINE = ReplacingMergeTree()
ORDER BY `datetime`
PRIMARY KEY `datetime`;
"""

# Execute the CREATE TABLE command
client.command(create_table_sql)

# Recursively search for CSV files with the specified prefix in csv_folder_path and its subdirectories
for root, dirs, files in os.walk(csv_folder_path):
    for filename in files:
        if filename == f"{file_prefix}.csv":
            print(f"Inserting {filename}...")
            file_path = os.path.join(root, filename)
            print(f"File path: {file_path}")  # Add this line for debugging
            # Use insert_file for efficient file inserts
            insert_file(client, table_name, file_path)
            print(f"Finished inserting {filename}.")


```

**Comment by arthur19q3** [comment]
> This is a general ClickHouse issue, not specific to `clickhouse-connect`.
> 
> By duplicates, do you mean multiple rows with the same `datetime` value, since that's your key?
> 
> A ReplacingMergeTree does not remove duplicates until an internal merge of dataparts occurs. You can avoid seeing duplicates in your queries by using a `FINAL` modifier in your `SELECT` query, or you can force merges using the `OPTIMIZE TABLE <table> FINAL` command.
> 
> There are many resources available discussing ReplacingMergeTrees and other strategies for removing duplicates from ClickHouse that should be available in both the official documentation and otherwise on the web.

thanks for the prompt reply, i have fixed the problem with execution of OPTIMISE command, just wondering is there any side effect to this?

**Comment by genzgd** [comment]
The main downsides to OPTIMIZE are (1) it is expensive, since it takes disk space, memory, and CPU to remove duplicates, and (2) you have to do it after adding any new data (although you can optimize only new partitions or otherwise minimize the actual amount of data that has to be rewritten).
