### ISSUE TITLE
cannot specify tuple structure with `external_file`

### ISSUE THREAD

**Issue by cpcloud** [ClickHouse/clickhouse-connect#242]
### Describe the bug

I get a 500 from the clickhouse server when I try to pass external data with a tuple field.

### Steps to reproduce

```python
import pyarrow as pa
import clickhouse_connect as cc

from clickhouse_connect.driver.external import ExternalData


def to_pyarrow_bytes(data):
    out = pa.BufferOutputStream()
    with pa.RecordBatchFileWriter(out, data.schema) as writer:
        writer.write(data)
    return out.getvalue()


if __name__ == "__main__":
    client = cc.get_client()

    external_data = ExternalData()
    raw_bytes = to_pyarrow_bytes(pa.Table.from_pydict({"my_col": [{"a": 1}]}))

    external_data.add_file(
        file_name="my_table",
        data=raw_bytes,
        structure="my_col Tuple(a Int64)",
        fmt="Arrow",
    )

    client.query_df("SELECT * FROM my_table", external_data=external_data)
```

Exception:

```
clickhouse_connect.driver.exceptions.DatabaseError: :HTTPDriver for http://localhost:8123 returned response code 500)
 Code: 36. DB::Exception: Odd number of attributes in section structure: 3. (BAD_ARGUMENTS) (version 23.8.2.7 (official build))
```

### Expected behaviour

No error.

#### Environment
* clickhouse-connect version: 0.6.10
* Python version: 3.10.12
* Operating system: Linux

#### ClickHouse server
* ClickHouse Server version: 23.8.2.7

**Comment by genzgd** [comment]
Do other datatypes work?  My guess is that ClickHouse itself doesn't support whatever a Tuple translates to when sent in Arrow format.  Regardless, there's unfortunately nothing in the `clickhouse-connect` code which can change how pyarrow and ClickHouse Arrow format work togther.

**Comment by cpcloud** [comment]
Other datatypes work.

I don't think it's data format issue though. I see the same issue regardless of what I use for `fmt`.

I just remembered that I opened https://github.com/ClickHouse/ClickHouse/issues/41112 a long time ago but it never seemed to receive any attention.

I suspect the server is splitting on spaces and not sending the structure through the parser.

**Comment by cpcloud** [comment]
In that issue I was trying to specify column names with spaces in them, but in this case I am unable to use the full set of types that clickhouse supports.

**Comment by cpcloud** [comment]
https://github.com/ClickHouse/ClickHouse/blob/master/src/Core/ExternalTable.cpp?plain=1#L59 seems relevant

**Comment by genzgd** [comment]
Indeed, that looks very suspicious.  Closing this in favor of the core ClickHouse issue.
