### ISSUE TITLE
Inserting an empty string to a FixedString column fails

### ISSUE THREAD

**Issue by georgipeev** [ClickHouse/clickhouse-connect#244]
### Describe the bug
Inserting an empty string to a `FixedString` column fails.
It also fails if the column is of type `Nullable(FixedString)`, although inserting a `None` value still works there.

### Steps to reproduce
1. Create a table with a `FixedString` column
2. Try inserting a record where the value for that column is an empty string

### Expected behaviour
This should work. The Clickhouse server will pad the empty string with nulls to whatever the fixed length is, as it does with strings of length less than the fixed length, and is the behavior I observe if I use the command-line tool `clickhouse-client`.

### Code example
```python
import clickhouse_connect
import pandas as pd

client = clickhouse_connect.get_client(...)
client.command("CREATE TABLE test (`i` Int64,  `s` FixedString(3)) ENGINE = MergeTree ORDER BY i")
client.insert_df("test", pd.DataFrame({"i": [1], "s": ["abc"]}))   # This works
client.insert_df("test", pd.DataFrame({"i": [2], "s": ["a"]}))   # This also works, "a" is padded by the server with \0
client.insert_df("test", pd.DataFrame({"i": [3], "s": [""]}))   # This fails
```

#### Environment
* clickhouse-connect version: 0.6.11
* Python version: 3.9.17
* Pandas version: 1.5.3
* Operating system: RHEL 8.6

#### ClickHouse server
* ClickHouse Server version: 23.4.1.1943

**Comment by genzgd** [comment]
Thanks for the report!  This will be fixed in the next release.  Just as general matter though I wouldn't recommend putting variable length strings into a FixedString column -- the padding functionality was mostly added for backward compatibility for some sample datasets which abused FixedString columns in that way.  Dealing with the 0x00 padded values is likely to cause weird issues in a lot of clients.

**Comment by georgipeev** [comment]
Dealing with the \0 padding and writing unit tests around that was how I found this problem.
