### ISSUE TITLE
Superset 2.1.1 clickhouse-connect Error with stored Metric in Dataset: clickhouse_connect.driver.exceptions.DatabaseError HTTPDriver for returned response code 500 Code: 215. DB::Exception: Column is not under aggregate function and not in GROUP BY

### ISSUE THREAD

**Issue by ivanshamaev** [ClickHouse/clickhouse-connect#262]
# Describe the bug
we updated the superset from `2.0.1` to `2.1.1`, during the update we replaced the driver for clikhouse (from the `clickhouse-connect>=0.6.8` official doc).

**Before we used driver:**
```
clickhouse-driver==0.2.0
clickhouse-sqlalchemy==0.1.6
```
After the update, we discovered that the metric saved in the dataset produces an error on the charts. But if instead of a saved metric you use a metric selection with an aggregation function or a custom sql expression, then everything works well.

When using a saved metric, the SQL query is not built correctly.
Example got from the superset's logs (error in Order By statement):

```
SELECT `property_id` AS `property_id_6bb837`,
       sum("Subscribers") AS `Subscribers_39f7a3`
FROM `default`.`counters`
GROUP BY `property_id`
ORDER BY `Subscribers` DESC
LIMIT 1000 on schema default
```
**_ORDER BY `Subscribers` DESC_** should be **_ORDER BY `Subscribers_39f7a3` DESC_**

# Steps to reproduce
1. Create a dataset
2. Go to edit the dataset and create a metric
![saved_metric_in_dataset](https://github.com/ClickHouse/clickhouse-connect/assets/16321084/052b5ac3-6e11-4543-a423-f7d1dbfee0e3)

3. Create a simple chart table and select 1 dimension and saved metric from the list of metrics
4. Click the "Create chart" button
![error_clickhouse_connect](https://github.com/ClickHouse/clickhouse-connect/assets/16321084/aefabaaf-827d-49f3-aed3-59adcf4ca993)

_clickhouse-connect and/or ClickHouse server logs
Issue Error: :HTTPDriver for http://xx.xxx.xxx.xxx:8123/ returned response code 500)
Code: 215. DB::Exception: Column Subscribers is not under aggregate function and not in GROUP BY. Have columns: ['sum(Subscribers)','property_id']: While processing Subscribers DESC. (NOT_AN_AGGREGATE) (version [23.9.2.56](https://23.9.2.56/) (official build))_

__File "/usr/local/lib/python3.8/site-packages/clickhouse_connect/driver/httpclient.py", line 357, in error_handler
raise OperationalError(err_str) if retried else DatabaseError(err_str) from None
clickhouse_connect.driver.exceptions.DatabaseError: :HTTPDriver for http://xx.xxx.xxx.xxx:8123/ returned response code 500)_

# Configuration
## Environment
**clickhouse-connect version:** >=0.6.8
**Python version:** ARG PY_VER=3.8.16-slim
**Operating system:**
```
Collecting clickhouse-connect>=0.6.8
Downloading clickhouse_connect-0.6.18-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (973 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 973.5/973.5 kB 18.2 MB/s eta 0:00:00
Collecting zstandard
Downloading zstandard-0.22.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (5.4 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.4/5.4 MB 56.4 MB/s eta 0:00:00
Requirement already satisfied: pytz in /usr/local/lib/python3.8/site-packages (from clickhouse-connect>=0.6.8->-r requirements/requirements-local.txt (line 1)) (2021.3)
Requirement already satisfied: certifi in /usr/local/lib/python3.8/site-packages (from clickhouse-connect>=0.6.8->-r requirements/requirements-local.txt (line 1)) (2021.10.8)
Requirement already satisfied: urllib3>=1.26 in /usr/local/lib/python3.8/site-packages (from clickhouse-connect>=0.6.8->-r requirements/requirements-local.txt (line 1)) (1.26.6)
Collecting lz4
Downloading lz4-4.3.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.3 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 115.6 MB/s eta 0:00:00
Installing collected packages: zstandard, lz4, clickhouse-connect
```

# ClickHouse server
ClickHouse Server version: version 23.9.2.56 and version 21.11.3.6 (official build)

**Comment by genzgd** [comment]
Does it work properly with clickhouse-driver/clickhouse sql-alchemy?   This seems like something related to how Superset itself builds queries and uses aliases, which is generally independent of the driver.

**Comment by ivanshamaev** [comment]
Thank you a lot for your note, I will try to check the connection to the clickhouse with sqlalchemy.
I can say for sure that everything works correctly in postgresql (tested).

**Comment by ivanshamaev** [comment]
I found a solution. It is necessary that the name of the metric be different from the name of the field in the dataset. Then no error occurs.
For now, this option suits us as a workaround.
![saved_metric_in_superset_211](https://github.com/ClickHouse/clickhouse-connect/assets/16321084/233f6ee8-32fc-456a-be2f-ce82e8cffb83)
