### ISSUE TITLE
Error on insert a date out of range in Nullable(Date) instead of 1970-01-01

### ISSUE THREAD

**Issue by marzoli** [ClickHouse/clickhouse-connect#271]
If I try to insert a date outside the allowed range (<1970-01-01) for a Nullable(Date) type (for example 1900-01-01), the driver throw an Error.

However, if I use other Python drivers (e.g. clickhouse-driver) or if I execute a manual SQL insert (INSERT INTO test VALUES (toDate('1900-01-01')) the value 1970-01-01 is inserted instead of generating the error.

The error:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/clickhouse_connect/driver/transform.py", line 102, in chunk_gen
    col_type.write_column(data, output, context)
  File "/home/airflow/.local/lib/python3.11/site-packages/clickhouse_connect/datatypes/base.py", line 202, in write_column
    self.write_column_data(column, dest, ctx)
  File "/home/airflow/.local/lib/python3.11/site-packages/clickhouse_connect/datatypes/base.py", line 217, in write_column_data
    self._write_column_binary(column, dest, ctx)
  File "/home/airflow/.local/lib/python3.11/site-packages/clickhouse_connect/datatypes/temporal.py", line 48, in _write_column_binary
    write_array(self._array_type, column, dest)
  File "/home/airflow/.local/lib/python3.11/site-packages/clickhouse_connect/driver/common.py", line 57, in write_array
    raise DataError('Unable to create Python array.  This is usually caused by trying to insert None ' +
clickhouse_connect.driver.exceptions.DataError: Unable to create Python array.  This is usually caused by trying to insert None values into a ClickHouse column that is not Nullable

**Comment by genzgd** [comment]
I don't consider this a bug.  If the application owner specifically wants to insert `1970-01-01` for dates that are outside of the valid range, they should convert invalid dates to the desired "default" before the insert.  Otherwise there is a risk of losing data or not detecting bad data from their input source.

**Comment by marzoli** [comment]
I understand however the behavior is different compared to the standard because if you execute a DIRECT SQL in ClickHouse (INSERT INTO ...), it itself converts the value out of range to the Default (1970-01-01 is default in CH) without generating an error. And all drivers follow this behavior. A warning would help identify a problem and avoid having to do a complete scan of the data before inserting it.

Eventually I'll do a fork. Thank you

**Comment by genzgd** [comment]
I don't think you can call inserting a default value of Jan 1, 1970 as the "standard" for inserted dates that are out of range.  Someone coming from Oracle or MySQL would not expect that behavior.  While it's standard for the ClickHouse SQL dialect, I don't think that's a great approach for a modern Python client where many new users won't be familiar with the range limitations of the ClickHouse Date type.

It's true that `clickhouse-driver` does automatically convert out of range dates to the `0` default, so I agree it would be good to flag this as an incompatibility with that driver.  However, other mainstream drivers do not do throw an error.  `ClickHouse JDBC/Java` will throw an error that looks like this:  `Date(-25567) should be between 0 and 65535 inclusive of both values`, while `clickhouse-go` returns: `clickhouse: dateTime overflow. Col1 must be between 1970-01-01 and 2106-01-01`

I could see improving the error message, but that represents a (small) tradeoff with performance as it would be necessary to do an explicit range check before converting the Date column to a native format integer.

Finally if you really need this behavior you might consider a PR making it configurable.
