### ISSUE TITLE
How to connect to a Clickhouse cluster using clickhouse-connect？

### ISSUE THREAD

**Issue by GlassyAmadeus** [ClickHouse/clickhouse-connect#272]
How to connect to a Clickhouse cluster using clickhouse-connect？

**Comment by genzgd** [comment]
ClickHouse doesn't have a specific "cluster" API, you always connect to a single node.  Please see the [documentation](https://clickhouse.com/docs/en/integrations/python#establish-a-connection) for how to connect.

There is a [enhancement request](https://github.com/ClickHouse/clickhouse-connect/issues/74) for using `clickhouse-connect` against multiple nodes, but the desired behavior hasn't been determined (although round robin HTTP connections against a host list is probably the most likely implementation).  However, that issue doesn't currently have high priority, so for the foreseeable future your application will have to determine what nodes to connect to with the client.

Please add any additional thoughts/requirements you might have to the[ "multiple host issue"](https://github.com/ClickHouse/clickhouse-connect/issues/74).
