### ISSUE TITLE
Support Nothing type in SQLAlchemy

### ISSUE THREAD

**Issue by elchyn-cheliabiyeu** [ClickHouse/clickhouse-connect#278]
Need to support queering views with Nothing typed columns in superset. Now have this error message:
`Unrecognized ClickHouse type base: Nothing name: Nullable(Nothing)`

Tried to simply add 
```
class Nothing(ChSqlaType, UserDefinedType):
    python_type = None
```
to `clickhouse_connect/cc_sqlalchemy/datatypes/sqltypes.py` and it seems fine, but I need help to investigate is it enough, what also should I do to fully support it.

**Comment by genzgd** [comment]
I think that should be fine, I believe that's just an oversight.

**Comment by elchyn-cheliabiyeu** [comment]
Okay, I can create PR
