### ISSUE TITLE
How to get the result information, if a client.command function gets wrong, now time can't  distinguish the success result and the fail resullt

### ISSUE THREAD

**Issue by HADES-S** [ClickHouse/clickhouse-connect#286]
now time can't  distinguish the success result and the fail resullt

querySummary has no information about It

https://github.com/ClickHouse/clickhouse-connect/blob/main/clickhouse_connect/driver/summary.py

**Comment by genzgd** [comment]
What command in particular are you thinking has a "fail result" and "success result?"  If you get a QuerySummary object back, ClickHouse returned no data in the response.

**Comment by genzgd** [comment]
No additional info provided.
