### ISSUE TITLE
clickhouse connect doesn't seem to be working with the clickhouse playground

### ISSUE THREAD

**Issue by cpcloud** [ClickHouse/clickhouse-connect#289]
### Describe the bug

I can't seem to get results in any format from the clickhouse playground

### Steps to reproduce

```
In [45]: import clickhouse_connect as cc

In [46]: con = cc.get_client(host="play.clickhouse.com", port=443, user="play", password="", secure=True)

In [47]: con.query_df("select 1 as a union all select 2 as a")
Out[47]:
Empty DataFrame
Columns: []
Index: []
```

### Expected behaviour

I would expect a DataFrame with two rows with a single column `a`.

### Code example

See the reproducer code above

#### Environment
* clickhouse-connect version: 0.6.23
* Python version: Python 3.10
* Operating system: Linux

#### ClickHouse server
* ClickHouse Server version: not sure
* ClickHouse Server non-default settings, if any: none
* `CREATE TABLE` statements for tables involved: none

**Comment by genzgd** [comment]
There is currently a bug with HTTP compression on the version of ClickHouse used at `play.clickhouse.com`.  Can you add the paramater `compression=None` to the `get_client` call and see if it works?

**Comment by genzgd** [comment]
Cool, I'll close this when a fixed version has been deployed to play.clickhouse.com.

**Comment by cpcloud** [comment]
Thanks for your help!

**Comment by genzgd** [comment]
ClickHouse version `24.1.1.1455` currently deployed on `play.clickhouse.com` appears to fix this issue.
