### ISSUE TITLE
Clickhouse schema not being retrieved with superset

### ISSUE THREAD

**Issue by arun11299** [ClickHouse/clickhouse-connect#293]
OS version: Ubuntu 22.04
Clickhouse Version: 24.1.1.923

I am following the steps mentioned in https://clickhouse.com/blog/visualizing-data-with-superset
Please note that I have been trying to make superset work with clickhouse for the last 4-5 hours and have tried all types of superset installation. Nothing worked. I am more inclined to believe that it is a superset issue. But expecting to get a better response here.

Repro steps:
1. Follow the exact steps from the above link.
2. Had to run clickhouse on the docker0 IP address so that the docker containers could access my clickhouse instance which is running on my machine.
3. Add clickhouse database to superset. Worked.
4. Go to SQL lab. No schema to select for my database.

I see below error in superset:
```
superset_app          | Traceback (most recent call last):
superset_app          |   File "/app/superset/models/core.py", line 198, in function_names
superset_app          |     return self.db_engine_spec.get_function_names(self)
superset_app          |   File "/app/superset/db_engine_specs/clickhouse.py", line 287, in get_function_names
superset_app          |     names = database.get_df(
superset_app          |   File "/usr/local/lib/python3.9/site-packages/pandas/core/frame.py", line 3761, in __getitem__
superset_app          |     indexer = self.columns.get_loc(key)
superset_app          |   File "/usr/local/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3655, in get_loc
superset_app          |     raise KeyError(key) from err
superset_app          | KeyError: 'name'

```

Could someone help with the exact steps (maybe with specific versioning) on how to get it to work ? Or even please recommend some UI which is not such a PITA to install and just works (like clickhouse :))

**Comment by genzgd** [comment]
Hi, I'm sorry for your frustrating experience.  Unfortunately there's a significant bug with HTTP compression in the most recent master version of ClickHouse.  If you can use a version of ClickHouse earlier than 24.1, it should work.  Alternatively you can send a "custom setting" in the connection dialog or uri of "compression=0" to turn off compression.

Like https://github.com/ClickHouse/clickhouse-connect/issues/289, I'll keep this open until the bad master/play.clickhouse.com version is fixed and no longer installed by default.

**Comment by genzgd** [comment]
This should be fixed if you install the latest ClickHouse version `24.1.1.1455` from master or using `curl https://clickhouse.com/ | sh`.  If you could have a chance to validate the fix that would be much appreciated.

**Comment by arun11299** [comment]
Thanks. I will check it.

**Comment by arun11299** [comment]
I can confirm that this works! Thanks for the quick response. Appreciate it.
