### ISSUE TITLE
Need to implement pooling of clickhouse clients for multi-threaded applications

### ISSUE THREAD

**Issue by shiva1998-R** [ClickHouse/clickhouse-connect#295]
**I am trying to use clickhouse in a multi threaded python application.**
When I am trying to do so, I am facing following error:
`clickhouse_connect.driver.exceptions.ProgrammingError: Attempt to execute concurrent queries within the same session.Please use a separate client instance per thread/process.` I tried using pool_mgr argument but no luck.

**Provide some way to use pools of connections**
Please provide some way of using db pooling of clickhouse clients from which I can request connections in a thread.

**Comment by genzgd** [comment]
There are suggestions for how to do this in the documentation, and specifically for handling that error.  Please see https://clickhouse.com/docs/en/integrations/python#managing-clickhouse-session-ids.  The short version -- assign your own unique `session_id` per client when calling `get_client`, or use `common.set_setting('autogenerate_session_id', False) `
