### ISSUE TITLE
Simple JSON select fails miserably

### ISSUE THREAD

**Issue by pkit** [ClickHouse/clickhouse-connect#298]
```python
import clickhouse_connect

client = clickhouse_connect.get_client(host='localhost')
print(client.query("""
SELECT * FROM format(JSONEachRow, 'data JSON', $${"data": {"a":1}}$$)
""").result_set)
```
Will fail with:
```
Traceback (most recent call last):
  File "/home/user/git/project/tt.py", line 6, in <module>
    """).result_set)
         ^^^^^^^^^^
  File "/home/user/git/project/.venv/lib/python3.11/site-packages/clickhouse_connect/driver/query.py", line 254, in result_set
    return self.result_rows
           ^^^^^^^^^^^^^^^^
  File "/home/user/git/project/.venv/lib/python3.11/site-packages/clickhouse_connect/driver/query.py", line 272, in result_rows
    for block in stream:
  File "/home/user/git/project/.venv/lib/python3.11/site-packages/clickhouse_connect/driver/common.py", line 195, in __next__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/user/git/project/.venv/lib/python3.11/site-packages/clickhouse_connect/driver/query.py", line 292, in _row_block_stream
    for block in self._column_block_stream():
  File "/home/user/git/project/.venv/lib/python3.11/site-packages/clickhouse_connect/driver/transform.py", line 75, in gen
    next_block = get_block()
                 ^^^^^^^^^^^
  File "/home/user/git/project/.venv/lib/python3.11/site-packages/clickhouse_connect/driver/transform.py", line 63, in get_block
    raise StreamFailureError(message) from None
clickhouse_connect.driver.exceptions.StreamFailureError: 
```

Same thing in `clickhouse-client`:
```
cc85a1e2bfab :) SELECT * FROM format(JSONEachRow, 'data JSON', $${"data": {"a":1}}$$)

SELECT *
FROM format(JSONEachRow, 'data JSON', '{"data": {"a":1}}')

Query id: 9ac11d9c-987c-496e-8573-aa68f0688552

┌─data────┐
│ {"a":1} │
└─────────┘

1 row in set. Elapsed: 0.001 sec. 
```
In more elaborate cases it will fail with:
```
Unrecognized ClickHouse type base:  name:
```
Yes, base is "" and name is "" too. :)
Probably the parser for types like `Object('json')` or `Array(Object('json'))` is pretty confused...

```
Connected to ClickHouse server version 23.8.1 revision 54465.

clickhouse-connect==0.7.0
```

**Comment by alexey-milovidov** [comment]
ClickHouse does not support the JSON data type.

**Comment by pkit** [comment]
I'm not sure... I do see docs about it.
https://clickhouse.com/docs/en/sql-reference/data-types/json
https://clickhouse.com/docs/en/integrations/data-formats/json

**Comment by alexey-milovidov** [comment]
The JSON data type is not supported: https://clickhouse.com/docs/en/sql-reference/data-types/json

**Comment by pkit** [comment]
I'm not sure it can be a tuple, if it's a real json type.
I.e. `{"a":1}\n{"b":"foo"}` what tuple it is? `Tuple(a In64, b String)`? Why? etc.
And it's not really a bug, 'cos `clickhouse-client` parses it perfectly. Or you're implying that it passes Tuple over TCP connection but something different for HTTP?
There's something that I still think is a problem: in my tests I've found out that different errors are returned for different queries, and sometimes even result is returned (wrong result). I would suspect that the C code is jumping all over the memory and not parsing the Native encoding correctly. Which is usually bad...

**Comment by genzgd** [comment]
The binary result I get back from contains the column type `Object('json')`, which `clickhouse-connect` doesn't even implement a deserializer for, because queries of jSON columns normally return either a Tuple (or alternative, an Array) column type.  Because there's no specific deserializer, the transform code return an invalid null result, causing the error you see.  This never gets to any C code, but the expected result does return a rather cryptic error. 

I suspect that ClickHouse client has some different binary/Native implementation to actually deserialize an `Object('json')` column, but given the downgraded status of the JSON type, I don't think it's worth digging through the ClickHouse C++ source code to implement it in `clickhouse-connect` for this edge case.

**Comment by pkit** [comment]
I think when I did `Array(JSON)` or something similar it returned `[(),(),()]`
So it does try to deserialize.
Ok.
