### ISSUE TITLE
Cannot parameterize both key and value in a query

### ISSUE THREAD

**Issue by ArmyDev** [ClickHouse/clickhouse-connect#304]
### Describe the bug
When trying to parametize both key and value in a clickhouse query, the latter returns always an empty array

### Steps to reproduce
This is one of the queries that gives me back incorrect data
```python
query = """
    SELECT DISTINCT
        rows
    FROM my_table
    WHERE company = {company:String} AND
        {tag:String} = {tagValue:String} AND
        format = 'TEXT' AND
        start <= {endTimestamp:UInt32} AND
        end >= {startTimestamp:UInt32}
"""

parameters = {
    'company': company,
    'tag': tag,
    'tagValue': tagValue,
    'startTimestamp': int(startTimestamp),
    'endTimestamp': int(endTimestamp)
}

request = connection.query(query, parameters)
```

#### Environment
* clickhouse-connect version: 0.6.8
* Python version: 3.8
* Operating system: Debian

#### ClickHouse server
* ClickHouse Server version: 23.7.1.2021

**Comment by genzgd** [comment]
`{tag:String} = {tagValue:String}` will compare two literal strings.  Assuming you want to compare the value of a column, you need to use the `Identifer` type, not `String`.  See the explanation of server side parameter binding [here](https://clickhouse.com/docs/en/interfaces/cli#cli-queries-with-parameters):

"It's also possible to pass table, database, column names as a parameter, in that case you would need to use Identifier as a data type."

**Comment by ArmyDev** [comment]
Didn't see that, thank you
