### ISSUE TITLE
full table name (including database) seems not working with insert_file() function

### ISSUE THREAD

**Issue by Kevin9436** [ClickHouse/clickhouse-connect#305]
### Describe the bug
when pass full table name to insert_file(), will raise table not exist exception

### Steps to reproduce
1. create database test
2. create table test.test_1
3. insert data with function insert_file(client, 'test.test_1', file_path)

### Expected behaviour
No exception.

### Code example
```python
from clickhouse_connect import get_client
from clickhouse_connect.driver.tools import insert_file

# create database test
# create table test.test_1
# then
insert_file(get_client(xxx), 'test.test_1', file_path, fmt='Parquet')
```

#### Environment
* clickhouse-connect version: 0.7.0
* Python version: 3.8.0
* Operating system: 

#### ClickHouse server
* ClickHouse Server version:
* ClickHouse Server non-default settings, if any:
* `CREATE TABLE` statements for tables involved:
* Sample data for these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary

**Comment by genzgd** [comment]
`insert_file` takes a `database` keyword that you can use instead of a full table name, but you're correct that using the full table name instead of the separate database argument is currently broken.  There should be a fix in the next release.
