### ISSUE TITLE
Unexpected timezone-aware return object for UTC query

### ISSUE THREAD

**Issue by tatjanapuskarov** [ClickHouse/clickhouse-connect#308]
### Describe the bug

When querying a `DateTime` column with the applied timezone being UTC, it is possible to get a timezone-aware datetime object as a response, even though a timezone-naive object is expected according to the [documentation](https://clickhouse.com/docs/en/integrations/python#time-zones):
> Note that if the applied timezone based on these rules is UTC, clickhouse-connect will always return a time zone naive Python datetime.datetime object. 

If `active_tz` evaluates to UTC according to [these rules](https://github.com/ClickHouse/clickhouse-connect/blob/8415839e87345677bb585820880918bd47aae718/clickhouse_connect/driver/query.py#L161C1-L172C38) and `local_tz` is not UTC, `active_tz` is set to UTC (and not `None`) because of [this check](https://github.com/ClickHouse/clickhouse-connect/blob/8415839e87345677bb585820880918bd47aae718/clickhouse_connect/driver/query.py#L175), even though `local_tz` should not be taken into account according to the `active_tz` setting precedence order. 

With `active_tz` being UTC and querying a `DateTime` column, the output is a timezone-aware object because of [this condition](https://github.com/ClickHouse/clickhouse-connect/blob/8415839e87345677bb585820880918bd47aae718/clickhouse_connect/datatypes/temporal.py#L124). For `DateTime64`, the output is a timezone-naive object because [the equivalent condition](https://github.com/ClickHouse/clickhouse-connect/blob/8415839e87345677bb585820880918bd47aae718/clickhouse_connect/datatypes/temporal.py#L174) includes an extra check.

### Expected behaviour

- The behaviour of `DateTime` and `DateTime64` types is expected to be consistent and should return a timezone-naive object regardless of whether `active_tz` is `None` or `'UTC'` (regardless of `local_tz`).
- The [documentation](https://clickhouse.com/docs/en/integrations/python#time-zones) should include usage of the local timezone.

### Code example
```python
import clickhouse_connect
import pytest
import pytz

with pytest.MonkeyPatch.context() as mp:
    mp.setattr("clickhouse_connect.driver.context.BaseQueryContext.local_tz", pytz.timezone('Pacific/Johnston')) # any non-UTC timezone 
    client = clickhouse_connect.get_client(
                host=…,
                port=…,
                username=…,
                password=…,
                database="default"
            )

   query = """
            SELECT
                datetime,
                datetime64
            FROM default.utc_bug
    """
    df = client.query_df(query)
    print(df[“datetime"].dt.tz is None)
    print(df[“datetime64"].dt.tz is None)
```

#### Environment
* clickhouse-connect version:  0.7.0

#### ClickHouse server
* ClickHouse Server version: 23.6.2.18
* `CREATE TABLE` statements for tables involved:
```
CREATE TABLE default.utc_bug
	(
	"datetime" DateTime('UTC'),
	"datetime64" DateTime64(3, 'UTC')
	)
	ENGINE = MergeTree
	ORDER BY "datetime";
```
	
* Sample data for these tables:
```
INSERT INTO default.utc_bug VALUES
	(now(), now());
```

**Comment by genzgd** [comment]
Thanks for the report!  Please verify the fix in 0.7.2 if possible.
