### ISSUE TITLE
Run tests against a SMT Cloud instance

### ISSUE THREAD

**Issue by mshustov** [ClickHouse/clickhouse-connect#309]
Run tests against a Cloud instance with SMT. Credentials are available via env vars
- INTEGRATIONS_TEAM_TESTS_CLOUD_HOST_SMT
- INTEGRATIONS_TEAM_TESTS_CLOUD_PASSWORD_SMT

**Comment by genzgd** [comment]
Still a couple of test failures left, was running the wrong workflow.

**Comment by genzgd** [comment]
One final issue left with JOIN and external Parquet data.  That test is skipped in the Cloud for now.
