### ISSUE TITLE
Can't insert into table with two-dimensional nested column using .insert()

### ISSUE THREAD

**Issue by siberianhunger** [ClickHouse/clickhouse-connect#314]
### Steps to reproduce
1. Trying to use this example https://github.com/ClickHouse/clickhouse-connect/blob/main/examples/insert_examples.py
but with slightly different table definition:
```sql
CREATE TABLE test_nested_flat
(
    `key` UInt32,
    `value` Nested(str String, second_dimension Nested(id Nullable(Int32), name Nullable(String)))
)
ENGINE = MergeTree
ORDER BY key
```
2. I'm struggling to figure out the syntax for second dimension nested column. I have tried:
```python
    # Note the Nested 'value' column is inserted as two parallel arrays of values
    # into their own columns of the form `col_name.key_name` with Array data types
    data = [
        [
            1, ['string_1', 'string_2'], [[[20, 30]], [['2d_str_1', '2d_str_2']]]
        ],

        [
            2, ['string_3', 'string_4'], [[[40, 50]], [['2d_str_3', '2d_str_4']]]
        ]

    ]
    client.insert('test_nested_flat', data,
                  column_names=['key', 'value.str', 'value.second_dimension'],
                  column_type_names=['UInt32', 'Array(String)',
                                     'Array(Nested(id Nullable(Int32), name Nullable(String)))'])
```
which is breaks with the following error:
`
clickhouse_connect/datatypes/container.py", line 237, in <genexpr>
    array_sample = [[tuple(sub_row[key] for key in keys) for sub_row in row] for row in sample]
TypeError: list indices must be integers or slices, not str
`

### Expected behaviour
It's actually inserts some data

### Configuration
default docker image (running it with compose)
#### Environment
* clickhouse-connect version: 0.7.0
* Python version: 3.10.9
* Operating system:  Ubuntu 20.04.3 LTS

#### ClickHouse server
* ClickHouse Server version: 22.1.3.7

**Comment by genzgd** [comment]
Are you using the setting "flatten_nested=1"?

I certainly wouldn't recommend a multi-dimensional Nested column (indeed I think the Nested approach is very confusing as it is, and other container types are better for most use cases), but the point of the example is that when inserting into a Nested column with `flatten_nested=1`, you don't actually use the `Nested` column type.  So when you define your column type for the second level, that would also have to be two parallel arrays.

Do you have an example of how do to this in plain SQL using the `ClickHouse` CLI client?

**Comment by siberianhunger** [comment]
> Are you using the setting "flatten_nested=1"?
>  Yes, I'm trying to edit `inserted_nested_flat()` from [this example](https://github.com/ClickHouse/clickhouse-connect/blob/main/examples/insert_examples.py)

> I certainly wouldn't recommend a multi-dimensional Nested column (indeed I think the Nested approach is very confusing as it is, and other container types are better for most use cases), but the point of the example is that when inserting into a Nested column with `flatten_nested=1`, you don't actually use the `Nested` column type. So when you define your column type for the second level, that would also have to be two parallel arrays.
> So I should have used some json type all along?
 
> Do you have an example of how do to this in plain SQL using the `ClickHouse` CLI client?
> For table like this:
`
CREATE TABLE test_nested_flat
(
    `key` UInt32,
    `value` Nested(str String, second_dimension Nested(id Nullable(Int32), name Nullable(String)))
)
ENGINE = MergeTree
ORDER BY key
`
Insert would look like this:
`
INSERT INTO test_nested_flat (
    key,
    value.str,
    value.second_dimension
) VALUES (
    1,
    ['value_123'],
    [[(1, 'second_dimension_str_1'),(2, 'second_dimension_str_1')]]
);
`

**Comment by genzgd** [comment]
> > I certainly wouldn't recommend a multi-dimensional Nested column (indeed I think the Nested approach is very confusing as it is, and other container types are better for most use cases), but the point of the example is that when inserting into a Nested column with `flatten_nested=1`, you don't actually use the `Nested` column type. So when you define your column type for the second level, that would also have to be two parallel arrays.
> 
> Why is that bad? I should have used some kind of json type for it all along? What would you recommend? Seems like json type is not really supported either... Should I use tuple type?
> 

You are correct that the experimental JSON type is not supported or recommended.  The ClickHouse team is working on a more stable replacement, but that will take some time.  Depending on your data, I would recommend a Map or a Tuple type, and I also usually recommend flattening the critical JSON fields before inserting into ClickHouse, as flattened fields will provide the best performance and simplest queries.

> > Do you have an example of how do to this in plain SQL using the `ClickHouse` CLI client?
> 
> For table like this:
> 
> ```sql
> CREATE TABLE test_nested_flat
> (
>     `key` UInt32,
>     `value` Nested(str String, second_dimension Nested(id Nullable(Int32), name Nullable(String)))
> )
> ENGINE = MergeTree
> ORDER BY key
> ```
> 
> Insert would look like this:
> 
> ```sql
> INSERT INTO test_nested_flat (
>     key,
>     value.str,
>     value.second_dimension
> ) VALUES (
>     1,
>     ['value_123'],
>     [[(1, 'second_dimension_str_1'),(2, 'second_dimension_str_1')]]
> );
> ```

Thanks, I will try to play with this over the next few days and see if I can make it work with `clickhouse-connect`.  This is inserting two parallel arrays (one of strings, one of arrays of tuples), so it's likely that the column types have to match that -- something like `['Int32', 'Array(String)', 'Array(Array(Tuple(Nullable(Int32), Nullable(String)))']`, but I have no idea if that would actually work.

**Comment by genzgd** [comment]
Closing this because using the column names  `['Int32', 'Array(String)', 'Array(Array(Tuple(Nullable(Int32), Nullable(String))))']` does in fact work.  In theory these column names could be automatically determined for "flattened" nested columns both one and two dimensional, but I don't believe it's worth the effort.
