### ISSUE TITLE
Make X-ClickHouse-Summary available through cursor API

### ISSUE THREAD

**Issue by elchyn-cheliabiyeu** [ClickHouse/clickhouse-connect#316]
We want to get summary information from the query we run using the cursor object. This field is not a specified cursor field, it only relates to clickhouse

**Comment by elchyn-cheliabiyeu** [comment]
I need an approval and will make MR for this

**Comment by genzgd** [comment]
I'm not sure what this would look like but it seems useful.  We're always happy to review community pull requests, but we do ask that you include tests for the new functionality.
