### ISSUE TITLE
Error when using external data from Arrow with boolean columns

### ISSUE THREAD

**Issue by cpcloud** [ClickHouse/clickhouse-connect#330]
### Describe the bug

Booleans in external arrow tables no longer work. Other types seem to work.

### Steps to reproduce

```python
import pyarrow as pa
import clickhouse_connect as cc

from clickhouse_connect.driver.external import ExternalData

c = cc.get_client()

table = pa.Table.from_pydict({"a": [True, False]})

out = pa.BufferOutputStream()
with pa.RecordBatchFileWriter(out, table.schema) as writer:
    writer.write(table)

table_bytes = out.getvalue()

external_data = ExternalData()
external_data.add_file(file_name="t", data=table_bytes, structure="a Bool", fmt="Arrow")

c.query("select * from t", external_data=external_data)
```

The error message I get is:

```
E       clickhouse_connect.driver.exceptions.DatabaseError: :HTTPDriver for http://localhost:8123 returned response code 500)
E        Code: 378. DB::Exception: Data type Bool cannot have arguments. (DATA_TYPE_CANNOT_HAVE_ARGUMENTS) (version 24.3.1.2672 (official build))
```

### Expected behaviour

I would expect booleans to work.

### Code example

See above.

#### Environment
* clickhouse-connect version: 0.7.4
* Python version: 3.12
* Operating system: Linux

#### ClickHouse server

* ClickHouse Server version:

```
❯ clickhouse client --query='select version()'
24.3.1.2672
```

**Comment by genzgd** [comment]
This is a ClickHouse error, and not related to ClickHouse connect.  Please create a reproducible example in `curl` and file an issue in the main ClickHouse repository.

**Comment by cpcloud** [comment]
https://github.com/ClickHouse/ClickHouse/issues/62108

**Comment by genzgd** [comment]
Thanks!
