### ISSUE TITLE
Using parameters in ADD COLUMN statement doesn't work

### ISSUE THREAD

**Issue by moshe-shaham-lumigo** [ClickHouse/clickhouse-connect#337]
### Describe the bug

this code doesn't work:
`
query = "ALTER TABLE {table_name:Identifier} ADD COLUMN {field_name:Identifier} Int64"
self._get_client().query(query=query, parameters={"table_name": table_name, "field_name": field_name})
`

This results in an error:
"Code: 62. DB::Exception: Syntax error: failed at position 48 ('{'): {field_name:Identifier}. Expected one of: IF NOT EXISTS, column declaration, compound identifier, list of elements, identifier. (SYNTAX_ERROR) (version 24.1.2.10900 (official build))\n"

It's important for me to use parameters, since the inputs can come from the user.
Is this supposed to work?

#### Environment
* clickhouse-connect version: **0.7.0**
* Python version: **3.9**
* Operating system: **mac/linux**

#### ClickHouse server
* ClickHouse Server version: **clickhouse cloud**
* ClickHouse Server non-default settings, if any:
* `CREATE TABLE` statements for tables involved:
* Sample data for these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary

**Comment by genzgd** [comment]
This is a known [issue](https://github.com/ClickHouse/ClickHouse/issues/42092) in ClickHouse.  Currently server side parameters are only guaranteed to work for `SELECT` statements.  I'll update the `clickhouse-connect` documents to mention that limitation.

**Comment by genzgd** [comment]
You can also try [client side binding](https://clickhouse.com/docs/en/integrations/python#client-side-binding).  Note that even though the input is supplied by the user, this doesn't really provide much of a SQL Injection attack vector.  Multi statements are not allowed, so all the user can really do is execute an `ALTER TABLE'
 statement on a table where they have permissions, and even in that case as a best practice you should sanitize your inputs to allow only valid table and column names.

**Comment by genzgd** [comment]
Docs added.  There's nothing more than can be done on the client side.
