### ISSUE TITLE
Keep-Alive doesn't keep connection open with ClickHouse Cloud environment

### ISSUE THREAD

**Issue by Sceosasciba** [ClickHouse/clickhouse-connect#340]
### Describe the bug
Not able to keep a connection open with ClickHouse Cloud. ClickHouse Cloud has a default keep-alive timeout of 10 seconds, but when I try to use the TCP options for the pool manager it doesn't seem to affect the connection. After exactly 10 seconds the connection will be closed. 

This causes a delay when a new query/ping is send after 10 seconds, as urllib3 first resets the connection before it can send the actual request. 

### Steps to reproduce
1. Set up a poolmanager with customised TCP settings 
2. Create a client with that poolmanager. 
3. Ping the client after an increasing interval. For example first after 9 seconds and then after 10 seconds.

### Expected behaviour
With the right KeepAlive TCP settings the connection should remain open, and after 10 seconds the client shouldn't have to open a new connection. 

From what we're seeing the KeepAlive packets are send to the CH Cloud environment, checked with tcpdump. Have not been able to read the request or response for the keep-alive packets, though. So I'm not sure if it's a bug in the client or I should contact CH Cloud support for this. 

### Code example
```python
import clickhouse_connect
from clickhouse_connect.driver import httputil
import time
import asyncio
import logging
from http.client import HTTPConnection

log = logging.getLogger("urllib3")
log.setLevel(logging.DEBUG)

ch = logging.StreamHandler()
ch.setLevel(logging.DEBUG)
log.addHandler(ch)
# print statements from `http.client.HTTPConnection` to console/stdout
HTTPConnection.debuglevel = 1

big_pool_mgr = httputil.get_pool_manager(maxsize=16, num_pools=12, verify=False, keep_idle=1, keep_interval=2)
client = clickhouse_connect.get_client("localhost", pool_mgr=big_pool_mgr) # I use a CH Cloud environment here instead of localhost

async def main() -> None:
    for i in range(9, 11):
        print("seconds to sleep:", i)
        await asyncio.sleep(i)
        start_time = time.time()
        client.ping()
        print("ping took:", time.time() - start_time)

asyncio.run(main())
```

### urllib3 log output (keep-alive packets won't appear in this)
seconds to sleep: 9
Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=0, status=None)
send: b'GET /ping HTTP/1.1\r\nHost: {host}\r\nAccept-Encoding: identity\r\nUser-Agent: python-urllib3/2.2.1\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Date: Mon, 15 Apr 2024 12:27:04 GMT
header: Connection: Keep-Alive
header: Content-Type: text/html; charset=UTF-8
header: Transfer-Encoding: chunked
header: Keep-Alive: timeout=10
header: X-ClickHouse-Summary: {"read_rows":"0","read_bytes":"0","written_rows":"0","written_bytes":"0","total_rows_to_read":"0","result_rows":"0","result_bytes":"0","elapsed_ns":"85191"}
{host} "GET /ping HTTP/1.1" 200 None
ping took: 0.007935047149658203
seconds to sleep: 10
Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=0, status=None)
**Resetting dropped connection: {host}**
send: b'GET /ping HTTP/1.1\r\nHost: {host}\r\nAccept-Encoding: identity\r\nUser-Agent: python-urllib3/2.2.1\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Date: Mon, 15 Apr 2024 12:27:14 GMT
header: Connection: Keep-Alive
header: Content-Type: text/html; charset=UTF-8
header: Transfer-Encoding: chunked
header: Keep-Alive: timeout=10
header: X-ClickHouse-Summary: {"read_rows":"0","read_bytes":"0","written_rows":"0","written_bytes":"0","total_rows_to_read":"0","result_rows":"0","result_bytes":"0","elapsed_ns":"76748"}
{host} "GET /ping HTTP/1.1" 200 None
ping took: 0.02130436897277832

#### Environment
* clickhouse-connect version: 0.7.2
* Python version: 3.11
* Operating system: MacOS/Linux (tried both)

#### ClickHouse server
* ClickHouse Server version: 24.1.2.10900
* ClickHouse Server non-default settings, if any: Running default CH Cloud environment.

**Comment by genzgd** [comment]
This statement is incorrect:  "With the right KeepAlive TCP settings the connection should remain open"

HTTP connections will be closed by the server if no new HTTP request is sent on the connection with the HTTP Keep Alive time.  That's unrelated to the TCP connection keep alives.
