### ISSUE TITLE
CH client fails to insert datetimes with Pandas >=2.1.x

### ISSUE THREAD

**Issue by lmdamato** [ClickHouse/clickhouse-connect#346]
### Describe the bug

I am trying to insert a pandas df to a CH table via the clickhouse-connect library. I am using pandas 2.1.0, and when doing so, the CH library fails due to this function not being found:

`pd.core.dtypes.common.is_datetime_or_timedelta_dtype`

The above function has been removed in pandas 2.1.x

### Steps to reproduce
1. Add ch_connect and Pandas >=2.1.x to a Python project's deps
2. Create a Dataframe with at least one datetime column
3. Run `ch_client.insert_df(df)`

### Expected behaviour

DF normally inserted to CH.

**Comment by genzgd** [comment]
What `clickhouse_connect` version are you using?  This was fixed in v0.6.11 and I just ran tests with Pandas 2.2.1 in my local environment.
