### ISSUE TITLE
How to upload nested data with insert_df

### ISSUE THREAD

**Issue by RobinFrcd** [ClickHouse/clickhouse-connect#348]
Hi,
I have pandas dataframe I want to upload to my clickhouse table, this table has nested fields.
How can I properly upload my data using `insert_df` ?

I tried:
- Set my nested fields to be a single column `nested` with dicts `{'a': ..., 'b':...}`
- Explode my nested column to multiple columns named `nested.a`, `nested.b`...

But I couldn't make it work, I either get `len` errors or `Unrecognized column 'nested'`.

What is the correct way to upload nested data using pandas dataframes ?

Thanks !

**Comment by genzgd** [comment]
Please see the discussion [here](https://github.com/ClickHouse/clickhouse-connect/issues/314) about the ClickHouse Nested data type.   I don't think you want that.  You might try a "named" Tuple instead.  If you can give a short example of the type of data you're trying to insert I can try to create an example when I get back in the office next week.

**Comment by RobinFrcd** [comment]
Named Tuple was indeed the solution here, thank you very much !
