### ISSUE TITLE
tzlocal dependency issue

### ISSUE THREAD

**Issue by drew-talon** [ClickHouse/clickhouse-connect#360]
### Describe the bug
Clickhouse-connect is incompatible with versions of tzlocal that are <4.0.b2
```
  File ".../site-packages/clickhouse_connect/driver/tzutil.py", line 29, in normalize_timezone
    local_name = tzlocal.get_localzone_name()
AttributeError: module 'tzlocal' has no attribute 'get_localzone_name'. Did you mean: 'get_localzone'?
```
This is hopefully a rare issue that I just happened to run across, feel free to reject the pr if you feel it is unnecessary.

### Steps to reproduce
1. Install tzlocal=3.0 
2. Install clickhouse-connect
3. import clickhouse

**Comment by genzgd** [comment]
Fix merged in 0.7.13
