### ISSUE TITLE
Queries ending with ';' return "Multi-statements are not allowed"

### ISSUE THREAD

**Issue by rogerjbos** [ClickHouse/clickhouse-connect#376]
### Describe the bug
In clickhouse_connect if you add a trailing ';' to a query it doesn't run and gives an error that "Multi-statements are not allowed."  The query will run just fine if you remove the semicolon.  Not sure if it is definitely a bug, but directly in clickhouse it is fine to end a query statement with a semicolon, so this behavior could be confusing for some.

### Steps to reproduce
1. client.query("select 1;")
2. client.query("select name from system.databases;")

#### Environment
* clickhouse-connect version: 24.6.2.17
* Python version: 3.12
* Operating system: mac

**Comment by genzgd** [comment]
That is not a valid clickhouse-connect version (it's a ClickHouse version).  This is a duplicate of #310 and should have been fixed in clickhouse-connect v0.7.2?

**Comment by rogerjbos** [comment]
Ok.  Thanks.
