### ISSUE TITLE
UID not found if running inside docker with non root privileages

### ISSUE THREAD

**Issue by mittalsuraj18** [ClickHouse/clickhouse-connect#380]
### Describe the bug
Getting the following error while running inside k8s
```python
 File "/usr/local/lib/python3.12/site-packages/clickhouse_connect/common.py", line 39, in build_client_name
    os_user = f'; os_user:{getpass.getuser()}'
                           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/getpass.py", line 169, in getuser
    return pwd.getpwuid(os.getuid())[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'getpwuid(): uid not found: 2000'
```
### Steps to reproduce
1. Install the latest version of clickhosue connect.
2. Build a docker file as root and then run the container as non root inside k8s

### Expected behaviour
1. Code should run

#### Environment
* clickhouse-connect version: 0.7.17
* Python version: 3.12
* Operating system: Linux ARM64

#### ClickHouse server
* ClickHouse Server version:
* ClickHouse Server non-default settings, if any:
* `CREATE TABLE` statements for tables involved:
* Sample data for these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary

**Comment by genzgd** [comment]
Thanks for the report -- there's a quick workaround until we release a fix.  Before creating a client, change the global setting for sending the os_user.

```python
from clickhouse_connect import common

common.set_setting('send_os_user', False)
```

**Comment by mittalsuraj18** [comment]
Thanks @genzgd that worked :)
