### ISSUE TITLE
DB-API cursor fetchone() and fetchmany() not returning rows

### ISSUE THREAD

**Issue by treysp** [ClickHouse/clickhouse-connect#385]
### Describe the bug

In some scenarios, the DB-API cursor fetch methods do not return rows that are available from an executed query:
- `fetchone()` incorrectly returns `None` to Python
- `fetchmany()` incorrectly returns `[]` to Python
-  `fetchall()` correctly returns all the rows

This may only occur on Clickhouse Cloud. Possibly a latency issue, but the bug still occurs after waiting between the execute() and fetchone() calls.

### Steps to reproduce

Reproduction is inconsistent - reproduces most of the time but occasionally works as expected.

1. Execute a SQL query returning at least one row with `cursor.execute()`
2. Call `cursor.fetchone()` or `cursor.fetchmany(n)`

### Expected behaviour

All `fetchXXX()` methods return rows if rows are available.

### Code example
```
> self.cursor.execute("select value from system.settings where name='cloud_mode'")
> self.cursor.fetchone()
> self.cursor.fetchmany(10)
[]
> self.cursor.fetchall()
[('1',)]
```

```
> self.cursor.execute("SELECT a from VALUES('a String', (1), (2))")
> self.cursor.fetchone()
> self.cursor.fetchone()
> self.cursor.fetchone()
> self.cursor.fetchone()
> self.cursor.fetchone()
> self.cursor.fetchone()
> self.cursor.fetchmany(1)
[]
> self.cursor.fetchall()
[('1',), ('2',)]
```

#### Environment
* clickhouse-connect version: 0.7.18
* Python version: 3.11.6
* Operating system: MacOS Ventura 13.4.1

#### ClickHouse server
* ClickHouse Cloud service version 24.5

**Comment by genzgd** [comment]
Are you reusing the same cursor at all?  I don't see any other way this can happen, the cursor implementation is very simple and all data is fetched at the beginning.  Cursors are definitely not thread safe or reusable.

**Comment by treysp** [comment]
Ah, I see now that neither `self._ix` or `self.data` are reset after all rows have been fetched.

So in a single thread should `cursor.close()` be called after every query execution that returns rows?

**Comment by genzgd** [comment]
This could definitely be improved.  cursor.close() doesn't currently make the cursor reusable, although arguably it should by setting self._ix to 0, and cursor.execute() should probably ensure that the cursor is in fact closed before being called again.
  
To be honest I haven't worried too much about it because as far as I know, only Superset actually uses the DB-API, and I personally wouldn't use DB-API code with `clickhouse-connect`, since it's so limiting.

**Comment by treysp** [comment]
Got it - thank you!
