### ISSUE TITLE
Support `log_comment` per query

### ISSUE THREAD

**Issue by pkit** [ClickHouse/clickhouse-connect#393]
Yes, I know that `client_name` and `product_name` are supported.
User agent is becomes pretty overloaded with strings: `client/product/clickhouse-connect/0.7.19 (lv:py/3.11.9; mode:sync; os:linux; os_user:user)`

`log_comment` lets differentiate queries on the query log on a per-query basis.

**Comment by genzgd** [comment]
You can do with with any existing query by using a `log_comment` setting:

```python
client.query('SHOW DATABASES', settings={'log_comment': 'A COMMENT'})
```
