### ISSUE TITLE
Date column gets cast to uint16 in Arrow

### ISSUE THREAD

**Issue by astrojuanlu** [ClickHouse/clickhouse-connect#394]
### Describe the bug

```
In [64]: r = client.query("SELECT * FROM pypi_downloads_per_month WHERE project = 'kedro'")

In [65]: r.named_results()
Out[65]: <generator object QueryResult.named_results at 0x13366e7a0>

In [66]: list(_)
Out[66]: 
[{'month': datetime.date(2024, 5, 1), 'project': 'kedro', 'count': 36036},
 {'month': datetime.date(2023, 5, 1), 'project': 'kedro', 'count': 401975},
 {'month': datetime.date(2023, 6, 1), 'project': 'kedro', 'count': 376471},
 {'month': datetime.date(2023, 7, 1), 'project': 'kedro', 'count': 339635},
...
```

but:

```
In [67]: t_ = client.query_arrow("SELECT * FROM pypi_downloads_per_month WHERE project = 'kedro'")

In [68]: t_
Out[68]: 
pyarrow.Table
month: uint16 not null
project: string not null
count: int64 not null
----
month: [[19844],[19478,19509,19539,19570],...,[19967],[19783,19814]]
project: [["kedro"],["kedro","kedro","kedro","kedro"],...,["kedro"],["kedro","kedro"]]
count: [[36036],[401975,376471,339635,345412],...,[92985],[527621,521359]]
```

(comes from `pypi_downloads_per_month` of clickpy https://clickhouse.com/blog/clickpy-one-trillion-rows)

### Expected behaviour

I get a proper Date column in Arrow?

### clickhouse-connect and/or ClickHouse server logs
?

#### Environment
* clickhouse-connect version: v0.7.19
* Python version: 3.11.9
* Operating system: macOS Sonoma 14.6.1

#### ClickHouse server
* ClickHouse Server version:
* ClickHouse Server non-default settings, if any:
* `CREATE TABLE` statements for tables involved:
* Sample data for these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary

**Comment by astrojuanlu** [comment]
(These seem to be days since UNIX epoch btw)

**Comment by genzgd** [comment]
Unlike the default/native formart `clickhouse-connect` doesn't do any conversion based on types for `Arrow` queries, it just returns what the PyArrow library does using the ClickHouse conversions here:  https://clickhouse.com/docs/en/interfaces/formats#data-format-arrow.  To stay consistent with ClickHouse, we don't intend to add any extra logic on top of either ClickHouse or PyArrow for particular data types.

**Comment by joe-clickhouse** [comment]
Hi @Ferdinanddb! `query_df_arrow()` is just a thin wrapper around the `query_arrow` methods so that's why you're seeing similar behavior. The server gives us a unit16 for Date cols when asking for [Arrow](https://clickhouse.com/docs/interfaces/formats/Arrow) format. However, once you have your Polars DataFrame casting a column from uint16 to `pl.Date` should be highly efficient with something like this:

```python
df = df.with_columns(pl.col("event_date").cast(pl.Date))
```
