### ISSUE TITLE
query_df return empty dataframe 

### ISSUE THREAD

**Issue by KirigiriSuzumiya** [ClickHouse/clickhouse-connect#401]
### Describe the bug
when query return large amount of rows, query_df return an empty dataframe. Only occured on new release 0.8.0,works well on 0.7.19
### Steps to reproduce
Easy to reproduce, when I run my query with `LIMIT 100 `,it works well.
Without LIMIT 100,returns empty dataframe

### Code example
```python
import clickhouse_connect
query = f"SELECT job_id, obj_val, timestamp, payload FROM events WHERE ( obj_name = 'state' ) AND ( org_id = 1 ) AND (scope = 'update:job')"
state_df = client.query_df(query=query)
```

#### Environment
* clickhouse-connect version:
* Python version:
* Operating system:

#### ClickHouse server
* ClickHouse Server version:
* ClickHouse Server non-default settings, if any:
* `CREATE TABLE` statements for tables involved:
* Sample data for these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary

**Comment by genzgd** [comment]
Please provide more information.  It is not "easy to reproduce" if we don't have your dataset.  How many rows are in the SELECT without the LIMIT?   Does it work if disable compression?   Does a regular `query` instead of `query_df` work?  Are there any errors in the ClickHouse server logs?
