### ISSUE TITLE
Postgresql connection results inconsistent

### ISSUE THREAD

**Issue by gabrielmcg44** [ClickHouse/clickhouse-connect#403]
### Describe the bug

I am migrating to use clickhouse-connect but I am facing a really weird problem when querying postgres tables

The whole test involves creating a testcontainer and a named collection. The test was working well with another clickhouse client.

Basically, depending on the filter, the queries do not return anything.

For example, if i run

```python
        result = await self.async_client.query(
            query=statement, settings={"session_id": "random_session_id"}
        )
        print(result.column_names)
``` 

With 4 different statements, I get:

- select * from postgresql(my_named_collection, table='my_table')
        where category = 'category_1'
Several results

- select * from postgresql(my_named_collection, table='my_table')
        where category = 'category_2'
Several results

- select * from postgresql(my_named_collection, table='my_table')
        where category != 'category_1'
Empty list

- select * from postgresql(my_named_collection, table='my_table')
Empty list

**Comment by genzgd** [comment]
What version are you using?  Is that behavior consistent?  Can you turn off compression?  This seems similar to https://github.com/ClickHouse/clickhouse-connect/issues/401, but I've not been able to reproduce it.

**Comment by gabrielmcg44** [comment]
I added this "select * from system.query_log" after two contradictory queries (running in sequence)

And the two of them returned the exactly the same result (tested in a text comparator)

[('QueryStart', datetime.date(2024, 10, 3), datetime.datetime(2024, 10, 3, 23, 36, 12), datetime.datetime(2024, 10, 3, 23, 36, 12, 676841), datetime.datetime(2024, 10, 3, 23, 36, 12), datetime.datetime(2024, 10, 3, 23, 36, 12, 676841), 0, 0, 0, 0, 0, 0, 0, 0, 'default', 'CREATE DATABASE IF NOT EXISTS my_database', '', 14222981827203494986, 'Create', ['my_database'], [], [], [], [], [], 0, '', '', 1, 'my_database', 'cb2526c6-ae8a-416d-a032-b5757bb8a72d', IPv4Address('127.0.0.1'), 48430, 'my_database', 'cb2526c6-ae8a-416d-a032-b5757bb8a72d', IPv4Address('127.0.0.1'), 48430, datetime.datetime(2024, 10, 3, 23, 36, 12), datetime.datetime(2024, 10, 3, 23, 36, 12, 676841), 1, 0, '', 'afaa0fa22e1e', 'ClickHouse client', 54465, 23, 8, 8, 0, '', '', '', '', 0, 54477, '', [], {}, {}, [], [], [], [], [], [], [], [], [], [], (0, 0, UUID('00000000-0000-0000-0000-000000000000')), 'Unknown', {}), ('QueryFinish', datetime.date(2024, 10, 3), datetime.datetime(2024, 10, 3, 23, 36, 12), datetime.datetime(2024, 10, 3, 23, 36, 12, 679330), datetime.datetime(2024, 10, 3, 23, 36, 12), datetime.datetime(2024, 10, 3, 23, 36, 12, 676841), 2, 0, 0, 0, 0, 0, 0, 0, 'default', 'CREATE DATABASE IF NOT EXISTS my_database', '', 14222981827203494986, 'Create', ['my_database'], [], [], [], [], [], 0, '', '', 1, 'my_database', 'cb2526c6-ae8a-416d-a032-b5757bb8a72d', IPv4Address('127.0.0.1'), 48430, 'my_database', 'cb2526c6-ae8a-416d-a032-b5757bb8a72d', IPv4Address('127.0.0.1'), 48430, datetime.datetime(2024, 10, 3, 23, 36, 12), datetime.datetime(2024, 10, 3, 23, 36, 12, 676841), 1, 0, '', 'afaa0fa22e1e', 'ClickHouse client', 54465, 23, 8, 8, 0, '', '', '', '', 0, 54477, '', [56], {'Query': 1, 'QueriesWithSubqueries': 1, 'FileOpen': 1, 'WriteBufferFromFileDescriptorWrite': 1, 'WriteBufferFromFileDescriptorWriteBytes': 78, 'FileSync': 1, 'FileSyncElapsedMicroseconds': 1530, 'IOBufferAllocs': 1, 'IOBufferAllocBytes': 141, 'DiskWriteElapsedMicroseconds': 8, 'ContextLock': 15, 'RealTimeMicroseconds': 2591, 'UserTimeMicroseconds': 966, 'SoftPageFaults': 17, 'OSCPUVirtualTimeMicroseconds': 966, 'OSWriteBytes': 4096, 'OSReadChars': 434, 'OSWriteChars': 1138, 'LogTrace': 3, 'LogDebug': 1, 'LogInfo': 3}, {}, [], [], ['Atomic'], [], [], [], [], [], [], [], (0, 0, UUID('00000000-0000-0000-0000-000000000000')), 'None', {})]

**Comment by gabrielmcg44** [comment]
Let me know if I can provide some more info

**Comment by gabrielmcg44** [comment]
Yes, the behavior is consistent. Tried the same test several times

**Comment by gabrielmcg44** [comment]
Tried it passing compress=False to where I create the client, and it worked!

But why? Should I keep it uncompressed? Wont I lose performance?

**Comment by genzgd** [comment]
What version of clickhouse-connect are you using?  There were changes to lz4 compression that might have a bug. In the meantime you can try 'zstd' compression instead

**Comment by gabrielmcg44** [comment]
just tried but zstd also fail

**Comment by genzgd** [comment]
Have you tried the latest 0.8.2 version?

**Comment by gabrielmcg44** [comment]
tested, 0.8.2 with zstd works, thanks

**Comment by genzgd** [comment]
If you have a chance, please test with lz4 as well (that's the default).
