### ISSUE TITLE
client.query_df returns wrong values

### ISSUE THREAD

**Issue by srhreza** [ClickHouse/clickhouse-connect#411]
### Describe the bug
After investigation about my result discrepancy I found that the same query using `clinet.query()` returns correct results but `client.query_df()` is giving me wrong answer.

### Steps to reproduce
1. correct_query_result = client.query("""SELECT  name,  COUNT(*)
                                FROM Some_CH_Table_dist
                                WHERE (name = 'Some_name') 
                                AND date_utc = '2024-10-10'
                                GROUP BY name;""")
                                
2. Wrong_query_result = client.query_df("""SELECT  name,  COUNT(*)
                                FROM Some_CH_Table_dist
                                WHERE (name = 'Some_name') 
                                AND date_utc = '2024-10-10'
                                GROUP BY name;""")

### Expected behaviour
Similar rusults
### Code example
```python
import clickhouse_connect
```

#### Environment
* clickhouse-connect version:
* Python version:
* Operating system:
UBUNTU

#### ClickHouse server
* ClickHouse Server version:
* ClickHouse Server non-default settings, if any:
* `CREATE TABLE` statements for tables involved:
```
     CREATE TABLE Some_CH_Table_rep ON CLUSTER cluster_2S_1R(
           name = String,
           date_utc = Date,
           ....
           ....
     )
     ENGINE = ReplicatedMergeTree()
           PRIMARY KEY (name, some_fileds)
PARTITION BY (country, toYYYYMM(date_utc))

CREATE TABLE Some_CH_Table_dist ON CLUSTER cluster_2S_1R
ENGINE = Distributed(cluster_2S_1R,Some_CH_Table_rep, rand())
```

* Sample data for these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary

**Comment by genzgd** [comment]
Please provide data where this reproduces.  Otherwise I presume this is related to having different data in the underlying tables on your cluster.

**Comment by srhreza** [comment]
Hi
I can't provide my data, my apologies. You just try it with some existing
data you have, it's quite clear. FYI, it took long time for me to find the
issue.

*Warm Regards*

*S**eyed **R**eza **H**asani (AI-Ph.D)*

*H/P: +1 778 751 1317*

**Comment by genzgd** [comment]
Unfortunately it is not clear, since many thousands of people use this code and no one has reported a similar issue.  What is "different"?  Can you create an artificial example with sample data?

**Comment by srhreza** [comment]
I can't really make some data to prove you there is something wrong, I have
you my table structure and I have you a query getting run with two methods.
This is enough for you to find the problem I guess.

I have used the query_df method in a lot my solutions, and now I need to go
back and verify all my results again. In this case the list of expected
results and the wrong results is provided
Wrong            Expected
1233592         1236988
755079.           762492
865226.           1628431 => almost half of actual results
905073.            813619
.
.
.

*Warm Regards*

*S**eyed **R**eza **H**asani (AI-Ph.D)*

*H/P: +1 778 751 1317*

**Comment by genzgd** [comment]
Again, I cannot reproduce this problem using the approach you describe.  The issue is likely with your ClickHouse setup.  Here's an example querying play.clickhouse.com, using the most recent `clickhouse_connect` version.

```python
import clickhouse_connect

client = clickhouse_connect.get_client(host="play.clickhouse.com", port=443, user="play", password="", secure=True)

df = client.query_df('SELECT radio, count(*) from cell_towers group by radio')
print(df)

result = client.query('SELECT radio, count(*) from cell_towers group by radio')
print(result.result_set)
```

As expected, this produces identicalresults:

```
  radio   count()
0  CDMA    556344
1   GSM   9931312
2   LTE  12101148
3    NR       867
4  UMTS  20686487
[('CDMA', 556344), ('GSM', 9931312), ('LTE', 12101148), ('NR', 867), ('UMTS', 20686487)]
```
