### ISSUE TITLE
There is no way to access the temporary table using the command method

### ISSUE THREAD

**Issue by IliyaGribenko** [ClickHouse/clickhouse-connect#420]
### Steps to reproduce
1.  Create clickhouse conenct

2. Create temporary table use command method

3. Create table with the same structure as temporary table use command method

4. Use command method and do query with REPALCE PARTITION between table and temporary table

### Expected behaviour
Library doesnt add database name "default" before temporary table

### Code example
```python

import clickhouse_connect

client_ch = clickhouse_connect.get_client(host=host, port=port, 
                                              username=username, password=password, 
                                              session_id=session_id, 
                                              settings={'session_timeout': session_timeout},
                                              )


 client_ch.command("CREATE TEMPORARY  TABLE IF NOT EXISTS `rate_euro_temporary`
(
`Date` Date,`Id` Nullable(String),`Nominal` Nullable(String),`Value` Nullable(Decimal(76, 4)),`VunitRate` Nullable(Decimal(76, 4))
)
ENGINE = MergeTree
PARTITION BY (Date)
ORDER BY Date
SETTINGS index_granularity = 8192;")


client_ch.command("CREATE TABLE IF NOT EXISTS `rate_euro`
(
`Date` Date,`Id` Nullable(String),`Nominal` Nullable(String),`Value` Nullable(Decimal(76, 4)),`VunitRate` Nullable(Decimal(76, 4))
)
ENGINE = MergeTree
PARTITION BY (Date)
ORDER BY Date
SETTINGS index_granularity = 8192;")


client_ch.command("ALTER TABLE `database`.rate_euro 
        REPLACE PARTITION '2024-10-17' FROM rate_euro_temporary")
```

##Error
File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_connect/driver/httpclient.py", line 461, in _raw_request
    self._error_handler(response)
  File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_connect/driver/httpclient.py", line 384, in _error_handler
    raise OperationalError(err_str) if retried else DatabaseError(err_str) from None
clickhouse_connect.driver.exceptions.DatabaseError: HTTPDriver for host received ClickHouse error code 497
 Code: 497. DB::Exception: client_name: Not enough privileges. To execute this query, it's necessary to have the grant SELECT ON default.rate_euro_temporary. (ACCESS_DENIED) (version 24.3.12.75 (official build))

#### Environment
* clickhouse-connect version:
* Python version:
* Operating system:

#### ClickHouse server
* ClickHouse Server version:
* ClickHouse Server non-default settings, if any:
* `CREATE TABLE` statements for tables involved:
* Sample data for these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary

**Comment by genzgd** [comment]
The library will never modify your SQL commands automatically.  It passes the `database` HTTP parameter, which may not be respected by the `ALTER TABLE` command even within the HTTP "session".  You can validate that behavior by using curl or another HTTP based client.  Regardless, this is not something that is safely "fixable" within `clickhouse-connect`.
