### ISSUE TITLE
Allow returning raw timestamp values instead of creatgin Python DateTIme objects

### ISSUE THREAD

**Issue by jmakov** [ClickHouse/clickhouse-connect#425]
Currently the client does it's own parsing and creates Python DateTime objects. Is it possible to disable that and only get the raw value - epoch timestamp CH is storing?

**Comment by IlluvatarEru** [comment]
Would be a great addition, especially as the conversion is sometimes taking forever (>3s) - which for realtime applications is not an option.

**Comment by genzgd** [comment]
The simplest way is to change your query -- SELECT reinterpretAsUInt32(dt_column) as epochTimestamp.  I'll look into adding a "read format" to support that particular use case.

**Comment by IlluvatarEru** [comment]
> The simplest way is to change your query -- SELECT reinterpretAsUInt32(dt_column) as epochTimestamp. I'll look into adding a "read format" to support that particular use case.

I am not sure about that solution:
```
CREATE TABLE example (
    dt DateTime64(3)  -- Precision: milliseconds
) ENGINE = Memory;

INSERT INTO example VALUES
    ('2024-11-19 15:44:46.123');

SELECT
    dt,
    reinterpretAsUInt32(dt) AS reinterpreted
FROM example
```
will get you:
`2024-11-19 15:44:46.123000+01:00	1155665835`

where `1155665835` is not the right unix timestamp here but rather: `Tuesday, August 15, 2006 6:17:15 PM`

**Comment by genzgd** [comment]
@IlluvatarEru:
DateTime64 values are Int64 values, so the reinterpret functions should be AsInt64
DateTime64(3) is an Int64 of epoch milliseconds
DateTime64(6) is an Int64 of epoch microseconds
DateTime64(9) is an Int64 of epoch nanoseconds

DateTime values are UInt32 of epoch seconds

**Comment by genzgd** [comment]
Okay, this is already implemented.  Please use the [read format](https://clickhouse.com/docs/en/integrations/python#read-formats) `int` for Date/DateTime/DateTime64 types.
