### ISSUE TITLE
Breaking change in version 0.8.8 : dates are now switched to localtime

### ISSUE THREAD

**Issue by Falgu9** [ClickHouse/clickhouse-connect#433]
### Describe the bug
Before version 0.8.8, when doing a `SELECT` query in a clickhouse table, `DateTime` type were selected as they were on the table.
It is now switched to the local time timezone.
### Steps to reproduce
1. Do a select query on a table containing a `DateTime` column
2.
3.

### Code example

```
$ echo $TZ
Europe/Paris
```
Before : 
```python
>>> import clickhouse_connect
>>> client = clickhouse_connect.get_client(host="127.0.0.1",port=8123,username="default",password="rootpass",)
>>> client.query("create database if not exists data")
>>> client.query("""CREATE OR REPLACE TABLE data.TEST_TABLE(
                                `DATE` DateTime('UTC'),
                            )
                            ENGINE = ReplacingMergeTree
                            PARTITION BY toYYYYMM(DATE)
                            PRIMARY KEY (DATE)
                            ORDER BY (DATE)
                            SETTINGS index_granularity = 8192;
                            """)

>>> client.query("select DATE_METER from data.EDE_SITE_RESULT_REAL_TIME limit 1").result_rows
[(datetime.datetime(2024, 9, 11, 20, 0),)]
```

Now : 
```python
>>> client.query("select DATE_METER from data.EDE_SITE_RESULT_REAL_TIME limit 1").result_rows
[(datetime.datetime(2024, 9, 11, 22, 0),)]
```

#### Environment
* clickhouse-connect version: 0.8.8 
* Python version: 3.12
* Operating system: Linux Ubuntu

#### ClickHouse server
* ClickHouse Server version:
* ClickHouse Server non-default settings, if any:
* `CREATE TABLE` statements for tables involved:
* Sample data for these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary

**Comment by genzgd** [comment]
Apologies, the function `datetime.utcfromtimestamp` I was using is targeted for deprecation, and the fix/update was incomplete.  I'll see if I can get a consistent fix.

**Comment by genzgd** [comment]
This turned out to be trickier than expected due to numpy (and possibly Pandas) conversions, so I've just reverted to the previous approach in the new 0.8.9 release.  Python datetimes are a mess, so I'll have to spend some more time to figure out how to get rid of the deprecation warnings.
