### ISSUE TITLE
Dynamic/Variant errors on insert (Code: 117. DB::Exception:)

### ISSUE THREAD

**Issue by EugeneIstomin** [ClickHouse/clickhouse-connect#441]
### Describe the bug
Some internal structures are incorrect when insert in Dynamic/Variant.

### Steps to reproduce
1. insert into datatypes like:
 - "Map(String, Variant(String, UInt128, Bool))",
 - "Map(String, Dynamic)",

### Expected behaviour
Insert successfully done.

### clickhouse-connect and/or ClickHouse server logs
Variant:  Code: 117. DB::Exception: Invalid version for SerializationVariant discriminators column.: While executing Native. (INCORRECT_DATA) (version 25.1.1.1751)
Dynamic: Code: 117. DB::Exception: Invalid version for Dynamic structure serialization: 4: While executing Native. (INCORRECT_DATA) (version 25.1.1.1751)

#### Environment
* clickhouse-connect version: 0.8.10
* Python version: 3.11/3.12
* Operating system: linux

#### ClickHouse server
* ClickHouse Server version: 24.11, 25.1.1 (from git repo)

**Comment by genzgd** [comment]
Thanks for the report -- it looks like you have the problem on both 24.11 and 25.1 -- I assume the behavior is the same on both?

**Comment by EugeneIstomin** [comment]
Yes, tested on both:
 - 24.11.1.2557
 - 25.1.1.1751
