### ISSUE TITLE
Question about format_query_value()

### ISSUE THREAD

**Issue by BooBSD** [ClickHouse/clickhouse-connect#47]
Hello.

I have a question: Why function `format_query_value()` wraps a result to quotes `''`? This behaviour makes it impossible to make complex queries with optional (empty) `WHERE` parts. Is it possible to change `format_query_value()` to make return result without quotes?

Thank you.

**Comment by genzgd** [comment]
Do you have some sample code and the query that is incorrectly formatted?  That function is only used in format strings and for SQLAlchemy, so avoiding it should be possible.

**Comment by BooBSD** [comment]
@genzgd 
Something like this:
```python
ch.query(
            """
            SELECT
                formatDateTime(started_at, '%%m/%%d/%%Y', %(time_zone)s) AS date,
                formatDateTime(started_at, '%%I:%%M:%%S %%p %(time_zone)s', %(time_zone)s) AS time,
                format('{}path/link?name={}&sn={}', %(portal_url)s, label, camera_sn) AS url,
                camera_name,
                description
            FROM recordings
            WHERE
                stack = %(stack)s
                %(where_company)s
                %(where_camera)s
                %(where_reviewed)s
                %(where_started_at)s
            ORDER BY started_at ASC
            """,
            {
                'time_zone': time_zone,
                'portal_url': 'http://example.com/',
                'stack': 'example',
                'where_company': f"AND company_id = '{company_id}'" if company_id != settings.DEFAULT_COMPANY else '',
                'where_camera': f"AND camera_sn = '{camera_id}'" if camera_id else '',
                'where_reviewed': "AND reviewed = true" if reviewed else '',
                'where_started_at': f"AND started_at BETWEEN {from}/1000 AND {to}/1000" if (from and to) else '',
            },
        ).result_set
```

There are next problems:

`formatDateTime(started_at, '%I:%M:%S %p 'UTC'', 'UTC') AS time,`

and

```
WHERE
    stack = 'example'
    ''
    ''
    ''
    'AND started_at BETWEEN 1234567890123/1000 AND 1234567890123/1000'
ORDER BY started_at ASC
```

**Comment by genzgd** [comment]
The format_query_value function is intended to format single values to ClickHouse SQL from native Python datatypes (that's why strings are quoted).  It has very simple logic and isn't designed for nesting or server side parameterization.

For a complex query like that I would suggest formatting everything but single values ClickHouse values in your application code before sending to the driver. 

Is there another tool you use (perhaps from another database) where that kind of formatting works?  I would certainly be open to expanding the query substitution functionality but I wouldn't even know where to start with the source query you have.  If there was some logic from another tool we could take a deeper look.

**Comment by BooBSD** [comment]
If I format a complex server-side query into a single SQL query with no parameters, this will lose the SQL injection protection from the `clickhouse_connect` library.

**Comment by genzgd** [comment]
You can still format the query with parameters, they just have to be a single Python value.  And it is safe to build and format a complex query as long as you don't include any unsanitized user input when building the query.  The key is to sanitize your user input -- i.e., validate that the `time_zone` value is a valid timezone, validate that the `company_id` and `camera_id` values are valid values (either by parsing the string or comparing against a lookup table, etc.) and not weird SQL phrases.

It is NOT safe to assume that passing your query through the `finalize_query` function will protect you from SQL injection attacks.  (In fact, the main protection it offers is escaping strings and putting them in quotes, the behavior you don't like).  ClickHouse Connect is a low level driver library that does no independent SQL validation and merely formats SQL that ClickHouse itself will parse.

Also unlike other databases, ClickHouse itself has no built in support for prepared statements and query statements/plans are not persisted on the server. Accordingly, with ClickHouse Connect (and most other ClickHouse libraries), it remains the responsibility of the application developer to ensure that only safe queries are sent to the ClickHouse server.

ClickHouse does have support for passing parameters via the query itself -- see https://clickhouse.com/docs/en/interfaces/http/#cli-queries-with-parameters.  Those are safe on the server side, but

- ClickHouse Connect does not currently implement that functionality directly (it is planned for a future release)
- Like the `format_query_value`, those parameters can only be used for a single ClickHouse column value, they do not work inside other text strings  (like your formatDateTime argument), and cannot be used to replace an entire SQL phrase.

**Comment by genzgd** [comment]
Also see this issue in the popular native protocol based Python driver:  https://github.com/mymarilyn/clickhouse-driver/issues/13.  That driver uses essentially the same parameterization approach as ClickHouse Connect.  As discussed above, it is not 100% foolproof, but it does prevent most basic SQL Injection attacks.
