### ISSUE TITLE
Wrong results for limit N BY .. in Apache superset

### ISSUE THREAD

**Issue by Lazycatsu** [ClickHouse/clickhouse-connect#53]
Very strange results using ORDER BY + LIMIT BY 

**Software:**
clkickhouse server v.22.1.3 rev.54455 (in docker)
clickhouse-connect v.0.2.10
superset (in docker)

**Data preparation:**
create table default.xxx
(day_id       Date,
attr1           int,
attr2           int,
 sale           Decimal64(2),
 updated_dt Datetime
 )
ENGINE = ReplacingMergeTree(updated_dt) PARTITION BY toYYYYMMDD(day_id)
ORDER BY (day_id, attr1, attr2)

insert into xxx
values( '2022-07-01', 1, 1, 100, now())
insert into xxx
values( '2022-07-01', 1, 1, 101, now())
insert into xxx
values( '2022-07-02', 1, 1, 200, now())
insert into xxx
values( '2022-07-02', 1, 2, 201, now())
insert into xxx
values( '2022-07-03', 1, 1, 200, now())
insert into xxx
values( '2022-07-03', 1, 2, 201, now())

**Query1 in SQLLab in superset:**

select day_id, updated_dt, sum(sale)
from default.xxx
where day_id between '2022-07-01' and '2022-07-02'
group by day_id, updated_dt
order by updated_dt DESC
limit 1 by day_id

**Results1 :**
[results1.csv](https://github.com/ClickHouse/clickhouse-connect/files/9732414/results1.csv)

**Query2 in SQLLab in superset**:

select * from (
select day_id, updated_dt, sum(sale)
from default.xxx
where day_id between '2022-07-01' and '2022-07-02'
group by day_id, updated_dt
order by updated_dt DESC
limit 1 by day_id
)
order by day_id

**Results2 :**
[results2.csv](https://github.com/ClickHouse/clickhouse-connect/files/9732403/results2.csv)

**Query3 in SQLLab in superset:**

select day_id, updated_dt, sum(sale)
from default.xxx
where day_id = '2022-07-01'
group by day_id, updated_dt
order by updated_dt desc
limit 1 by day_id

**Results 3:**
[results3.csv](https://github.com/ClickHouse/clickhouse-connect/files/9732390/results3.csv)

**Comment by genzgd** [comment]
Please be more explicit about what is "wrong" when posting an issue and what you expect to see instead.   Also, using now() as an update value is indeterminate -- is now() the same for your rows or has it changed by a second?  If it's the same your GROUP BY will has a different result.

In any case I cannot reproduce this on Superset 2.0.0 with ClickHouse 22.9 (that is, I don't get the same results as your CSV files):

![Screen Shot 2022-10-07 at 3 28 37 AM](https://user-images.githubusercontent.com/625882/194521817-e9a67915-f04f-47c5-a51f-3bb649cf02c7.png)

**Comment by Lazycatsu** [comment]
Sorry. wrong CSV (seems that's export's bug). And wrong show results. When chart created everything is allright.
