### ISSUE TITLE
Error running SET Statement

### ISSUE THREAD

**Issue by DerekChia** [ClickHouse/clickhouse-connect#59]
[SET Statement](https://clickhouse.com/docs/en/sql-reference/statements/set/) assigns value to the param setting for the current session, using the following syntax

```
SET param = value
```

However, when using it with client.query(), we get the following error. 

```
client.query('SET input_format_csv_use_best_effort_in_schema_inference=0')
```

```
HTTPDriver url https://xxx.us-west-2.aws.clickhouse.cloud:8443/ returned response code 400)
Code: 62. DB::Exception: Syntax error: failed at position 61 ('FORMAT') (line 2, col 2): FORMAT Native. Expected end of query. (SYNTAX_ERROR) (version 22.10.1.15995 (official build))
```

Is there a way to get this to work, especially for those that cannot be placed as part of the query statement but needs to be enabled beforehand? e.g. `SET allow_experimental_X=1`

**Comment by genzgd** [comment]
SET statements should be run using the `client.command` method and that should work.  But it makes sense to check for them in the query method and not apply a format, so I'll see if I can improve that.

**Comment by genzgd** [comment]
Also a SET statement requires that get_client be created with a `session_id`.

**Comment by genzgd** [comment]
Release 0.3.2 also sets a session_id by default.
