### ISSUE TITLE
QueryContext.updated_copy works incorrectly

### ISSUE THREAD

**Issue by trgtrg** [ClickHouse/clickhouse-connect#65]
https://github.com/ClickHouse/clickhouse-connect/blob/8d3b66a89638dff8d44b8315534e6b93ab4f1c5f/clickhouse_connect/driver/query.py#L117

Call of `self.parameters.update(parameters or {})` won't return updated copy, instead it returns None (https://docs.python.org/3/library/stdtypes.html#dict.update). It also updates current instance parameters! As a result QueryContext.updated_copy returns QueryContext with empty parameters and substitution does not work.

**Comment by genzgd** [comment]
Thanks for the detailed bug report.  This should be fixed in the 0.3.6 release.
