### ISSUE TITLE
Add package version number 

### ISSUE THREAD

**Issue by DerekChia** [ClickHouse/clickhouse-connect#76]
Add package version number (in [dunders format](https://peps.python.org/pep-0008/#module-level-dunder-names)) so that user can track the current installed version easily.

Example: `clickhouse_connect.__version__`

Reference: https://packaging.python.org/en/latest/guides/single-sourcing-package-version/

**Comment by genzgd** [comment]
As of 0.4.3, the VERSION file is now copied correctly into any distribution. 
 See option 4 of https://packaging.python.org/en/latest/guides/single-sourcing-package-version/. Using this file is somewhat more straightforward for CI/CD builds.
