### ISSUE TITLE
TypeError: Cannot interpret 'datetime64[ns, UTC]' as a data type

### ISSUE THREAD

**Issue by DerekChia** [ClickHouse/clickhouse-connect#77]
**Problem**

`pd.to_datetime()` produces `datetime64[ns, UTC]` data type that is not a sub dtype of `np.datetime64`

**Notebook to reproduce error**

https://gist.github.com/DerekChia/bbfd22d744f41ef6bdb5884d6ff62c8a

**Comment by genzgd** [comment]
Fixed in 0.4.2
