### ISSUE TITLE
JSON data insertion doesn't seem to work

### ISSUE THREAD

**Issue by pavanagrawal123** [ClickHouse/clickhouse-connect#84]
Whenever passing in native JSON data, we get an exception:
<img width="1407" alt="Screen Shot 2022-12-04 at 7 54 04 PM" src="https://user-images.githubusercontent.com/17802917/205532995-50320a02-6930-4fa7-a90e-49c320237725.png">

This occurs because, in the lower level `write_native_data` method, the `v` var is a string, which is being appended to a byte array. 
![image](https://user-images.githubusercontent.com/17802917/205533297-fee22086-e3a9-4ace-943b-3a62b9c4960c.png)

I fixed this locally by encoding the `v` var into `utf-8`. Do I misunderstand something in the insertion process that I need to correct in the client-level code?

If it helps to debug, the JSON library chosen by `clickhouse-connect` is `ujson`.

**Comment by genzgd** [comment]
Yes, this is a bug specifically with ujson.  orjson `dumps` returns bytes while ujson `dumps` returns a string, which I didn't catch in testing.

**Comment by pavanagrawal123** [comment]
Thanks so much, @genzgd , really appreciate the prompt reply and fix!

**Comment by genzgd** [comment]
Thanks for the detailed debugging information!
