### ISSUE TITLE
Weird rounding of floats without calculation

### ISSUE THREAD

**Issue by LordReaver** [ClickHouse/clickhouse-connect#86]
Given this scenario I would expect another outcome:

```
create table tmp_float_test
(
    flt Float32 default 0
)
    engine = MergeTree ORDER BY flt
        SETTINGS index_granularity = 8192;

INSERT INTO tmp_float_test(flt) VALUES (6.43);

SELECT flt from tmp_float_test ORDER BY flt ASC;

```

This gives flt: 6.43 as a result in DataGrip for example. But running this query in python gives another result:

```
data = clickhouse_client.query_dataframe("SELECT flt FROM tmp_float_test ORDER BY flt DESC;").to_dict("records")
print(data)  # [{'flt': 6.429999828338623}]
```

So is this a problem of the db itself or is it a problem of this package? As you can see there are no calculations involved, I'm just selecting that value and still it breaks. I could apply a rounding afterwards but that shouldn't be necessary in the first place.
For decimals this doesn't happen of course so should I just switch to decimals and forget about floats at all?

**Comment by genzgd** [comment]
I should mention that the Python Numpy library does have native Float32 datatype, so if you use the ClickHouse Connect query_np method (or presumably use numpy arrays in clickhouse-driver), you will get the expected value in the resulting numpy array:

```
client.query_np('SELECT flt FROM tmp_float_test ORDER BY flt DESC')
array([[6.43]], dtype=float32)
```
