### ISSUE TITLE
Code: 354. DB::Exception: inflateReset failed: buffer error: While executing Native. (ZLIB_INFLATE_FAILED)

### ISSUE THREAD

**Issue by YuriWerewolf** [ClickHouse/clickhouse-connect#93]
Using Python (pandas) to insert data into ClickHouse (24000 files (dataframes))
 ```
        df = pd.read_parquet(files[i], engine='fastparquet')
        df['t'] = pd.to_datetime(df['t'] * 1000000)    
        fname = os.path.basename(files[i])
        df['Ticker'] = fname[:len(fname)-8]
        df.dropna(inplace=True)
        client.insert_df('equities.m1m', df)
```
For some files (approx 1-2%) I (always) get the following error:
**Code: 354. DB::Exception: inflateReset failed: buffer error: While executing Native. (ZLIB_INFLATE_FAILED) (version 22.13.1.1561 (official build))**

I have checked the data for those and everything looks ok, ie size wise they are not big, values are ok etc.

How can i fix this error?

OS: Linux Mint 21.1 Cinnamon 5.6.5
Thanks

**Comment by YuriWerewolf** [comment]
with compress = False no issues with those files (dataframes)

`client = clickhouse_connect.get_client(host='localhost', username='default', compress = False) `

Reproducible example is harder as it is just dataframes with simple structure/data. Example is below, not the one that caused issues.

![image](https://user-images.githubusercontent.com/18197357/211649897-ac328f34-12fa-488d-a40b-06b1fe0eaad6.png)

**Comment by genzgd** [comment]
Thanks for the update!  I would leave compression off for now then (in the next release False will be the default anyway.)

I'll take a shot at reproducing the issue but the plan is actually to switch from gzip to zstd, so when that's released hopefully the problem will be irrelevant.

**Comment by genzgd** [comment]
It's possible that the JDBC driver has the same problem:  https://github.com/ClickHouse/clickhouse-jdbc/issues/721

**Comment by genzgd** [comment]
Closing this as the underlying ClickHouse server issue appears to be fixed.
