### ISSUE TITLE
Support for External Data for Query Processing

### ISSUE THREAD

**Issue by UnamedRus** [ClickHouse/clickhouse-connect#98]
From documentation it's not clear does this driver support external data

https://clickhouse.com/docs/en/engines/table-engines/special/external-data/

**Comment by genzgd** [comment]
It does not currently support external data.

**Comment by cpcloud** [comment]
Hi 👋🏻!

We'd love to use `clickhouse-connect` for [the Ibis project](https://github.com/ibis-project/ibis), and this is a big blocker for us to switch.
